/////////////////////////////////////////////////////////////////////////////////
// This file has been automatically generated by register_slave.pl version 81e8297
/////////////////////////////////////////////////////////////////////////////////

// type declaration
#ifndef __REG_CONST_T
#define __REG_CONST_T

#ifndef REG_CONST_NAME_STRING_MAX_LEN   
#define REG_CONST_NAME_STRING_MAX_LEN 64
#endif // REG_CONST_NAME_STRING_MAX_LEN
#ifndef REG_CONST_DESC_STRING_MAX_LEN
#define REG_CONST_DESC_STRING_MAX_LEN 512
#endif // REG_CONST_DESC_STRING_MAX_LEN
typedef struct {
	char name[REG_CONST_NAME_STRING_MAX_LEN];
	DWORD address;
	DWORD def;
	char desc[REG_CONST_DESC_STRING_MAX_LEN];
} reg_const_t;
typedef struct {
	char name[REG_CONST_NAME_STRING_MAX_LEN];
	char range[32];
	char def[32];
	char access[32];
	char desc[REG_CONST_DESC_STRING_MAX_LEN];
} field_const_t;
typedef struct {
	field_const_t *pfield;
	DWORD size;
} field_const_array_t;
#endif // __REG_CONST_T

#define NUM_REGS__DBGCAPTURE_REG  59
/* { reg_const_dbgcapture_reg, 59, "dbgcapture_reg"},  */ 
static reg_const_t reg_const_dbgcapture_reg[NUM_REGS__DBGCAPTURE_REG] = {
  {/* name */ "intr_status", /* address */ 0x4410e000, /* default */ 0x00000000, /* description */ "Interrupt status register bits. \n"}, 
  {/* name */ "intr_mask_status", /* address */ 0x4410e004, /* default */ 0x00000000, /* description */ "Interrupt mask status register\n"}, 
  {/* name */ "intr_clr", /* address */ 0x4410e008, /* default */ 0x00000000, /* description */ "Clear interrupt status\n"}, 
  {/* name */ "intr_set", /* address */ 0x4410e00c, /* default */ 0x00000000, /* description */ "Set interrupt status\n"}, 
  {/* name */ "intr_mask_set", /* address */ 0x4410e010, /* default */ 0x00000000, /* description */ "Set interrupt mask\n"}, 
  {/* name */ "intr_mask_clr", /* address */ 0x4410e014, /* default */ 0x00000000, /* description */ "Set interrupt mask\n"}, 
  {/* name */ "misc_ctrl", /* address */ 0x4410e040, /* default */ 0x0003f000, /* description */ "Basic control register\n"}, 
  {/* name */ "misc_ctrl_start_stop", /* address */ 0x4410e044, /* default */ 0x00000000, /* description */ "Basic control register for start and force stop\n"}, 
  {/* name */ "start_ctrl", /* address */ 0x4410e048, /* default */ 0x00000222, /* description */ "Basic control register\n"}, 
  {/* name */ "core_0_trig_sel_0", /* address */ 0x4410e080, /* default */ 0x00000000, /* description */ "Trigger selection for core 0\n"}, 
  {/* name */ "core_0_trig_sel_1", /* address */ 0x4410e084, /* default */ 0x00000000, /* description */ "Trigger selection for core 0\n"}, 
  {/* name */ "core_0_trig_cond", /* address */ 0x4410e088, /* default */ 0x00000000, /* description */ "Trigger condition for core 0\n"}, 
  {/* name */ "core_0_trig_mask", /* address */ 0x4410e08c, /* default */ 0x00000000, /* description */ "Trigger mask for core 0\n"}, 
  {/* name */ "core_0_data_src_sel", /* address */ 0x4410e090, /* default */ 0x00000000, /* description */ "Data source selection\n"}, 
  {/* name */ "core_0_qual_control", /* address */ 0x4410e094, /* default */ 0x00010000, /* description */ "Data qualifier control\n"}, 
  {/* name */ "core_0_status", /* address */ 0x4410e098, /* default */ 0x00000000, /* description */ "Core 0 status\n"}, 
  {/* name */ "core_0_addr", /* address */ 0x4410e09c, /* default */ 0x00000000, /* description */ "Core 0 address status\n"}, 
  {/* name */ "core_0_num_data", /* address */ 0x4410e0a0, /* default */ 0x00000000, /* description */ "Core 0 address status\n"}, 
  {/* name */ "core_0_rdata", /* address */ 0x4410e0b0, /* default */ 0x00000000, /* description */ "Core 0 read data\n"}, 
  {/* name */ "core_1_trig_sel_0", /* address */ 0x4410e0c0, /* default */ 0x00000000, /* description */ "Trigger selection for core 1\n"}, 
  {/* name */ "core_1_trig_sel_1", /* address */ 0x4410e0c4, /* default */ 0x00000000, /* description */ "Trigger selection for core 1\n"}, 
  {/* name */ "core_1_trig_cond", /* address */ 0x4410e0c8, /* default */ 0x00000000, /* description */ "Trigger condition for core 1\n"}, 
  {/* name */ "core_1_trig_mask", /* address */ 0x4410e0cc, /* default */ 0x00000000, /* description */ "Trigger mask for core 1\n"}, 
  {/* name */ "core_1_data_src_sel", /* address */ 0x4410e0d0, /* default */ 0x00000000, /* description */ "Data source selection\n"}, 
  {/* name */ "core_1_qual_control", /* address */ 0x4410e0d4, /* default */ 0x00010000, /* description */ "Data qualifier control\n"}, 
  {/* name */ "core_1_status", /* address */ 0x4410e0d8, /* default */ 0x00000000, /* description */ "Core 0 status\n"}, 
  {/* name */ "core_1_addr", /* address */ 0x4410e0dc, /* default */ 0x00000000, /* description */ "Core 0 address status\n"}, 
  {/* name */ "core_1_num_data", /* address */ 0x4410e0e0, /* default */ 0x00000000, /* description */ "Core 1 address status\n"}, 
  {/* name */ "core_1_rdata", /* address */ 0x4410e0f0, /* default */ 0x00000000, /* description */ "Core 1 read data\n"}, 
  {/* name */ "core_2_trig_sel_0", /* address */ 0x4410e100, /* default */ 0x00000000, /* description */ "Trigger selection for core 2\n"}, 
  {/* name */ "core_2_trig_sel_1", /* address */ 0x4410e104, /* default */ 0x00000000, /* description */ "Trigger selection for core 2\n"}, 
  {/* name */ "core_2_trig_cond", /* address */ 0x4410e108, /* default */ 0x00000000, /* description */ "Trigger condition for core 2\n"}, 
  {/* name */ "core_2_trig_mask", /* address */ 0x4410e10c, /* default */ 0x00000000, /* description */ "Trigger mask for core 2\n"}, 
  {/* name */ "core_2_data_src_sel", /* address */ 0x4410e110, /* default */ 0x00000000, /* description */ "Data source selection\n"}, 
  {/* name */ "core_2_qual_control", /* address */ 0x4410e114, /* default */ 0x00010000, /* description */ "Data qualifier control\n"}, 
  {/* name */ "core_2_status", /* address */ 0x4410e118, /* default */ 0x00000000, /* description */ "Core 2 status\n"}, 
  {/* name */ "core_2_addr", /* address */ 0x4410e11c, /* default */ 0x00000000, /* description */ "Core 2 address status\n"}, 
  {/* name */ "core_2_num_data", /* address */ 0x4410e120, /* default */ 0x00000000, /* description */ "Core 2 address status\n"}, 
  {/* name */ "core_2_rdata", /* address */ 0x4410e130, /* default */ 0x00000000, /* description */ "Core 2 read data\n"}, 
  {/* name */ "core_3_trig_sel_0", /* address */ 0x4410e140, /* default */ 0x00000000, /* description */ "Trigger selection for core 3\n"}, 
  {/* name */ "core_3_trig_sel_1", /* address */ 0x4410e144, /* default */ 0x00000000, /* description */ "Trigger selection for core 3\n"}, 
  {/* name */ "core_3_trig_cond", /* address */ 0x4410e148, /* default */ 0x00000000, /* description */ "Trigger condition for core 3\n"}, 
  {/* name */ "core_3_trig_mask", /* address */ 0x4410e14c, /* default */ 0x00000000, /* description */ "Trigger mask for core 3\n"}, 
  {/* name */ "core_3_data_src_sel", /* address */ 0x4410e150, /* default */ 0x00000000, /* description */ "Data source selection\n"}, 
  {/* name */ "core_3_qual_control", /* address */ 0x4410e154, /* default */ 0x00010000, /* description */ "Data qualifier control\n"}, 
  {/* name */ "core_3_status", /* address */ 0x4410e158, /* default */ 0x00000000, /* description */ "Core 3 status\n"}, 
  {/* name */ "core_3_addr", /* address */ 0x4410e15c, /* default */ 0x00000000, /* description */ "Core 3 address status\n"}, 
  {/* name */ "core_3_num_data", /* address */ 0x4410e160, /* default */ 0x00000000, /* description */ "Core 3 address status\n"}, 
  {/* name */ "core_3_rdata", /* address */ 0x4410e170, /* default */ 0x00000000, /* description */ "Core 3 read data\n"}, 
  {/* name */ "core_4_trig_sel_0", /* address */ 0x4410e180, /* default */ 0x00000000, /* description */ "Trigger selection for core 4\n"}, 
  {/* name */ "core_4_trig_sel_1", /* address */ 0x4410e184, /* default */ 0x00000000, /* description */ "Trigger selection for core 4\n"}, 
  {/* name */ "core_4_trig_cond", /* address */ 0x4410e188, /* default */ 0x00000000, /* description */ "Trigger condition for core 4\n"}, 
  {/* name */ "core_4_trig_mask", /* address */ 0x4410e18c, /* default */ 0x00000000, /* description */ "Trigger mask for core 4\n"}, 
  {/* name */ "core_4_data_src_sel", /* address */ 0x4410e190, /* default */ 0x00000000, /* description */ "Data source selection\n"}, 
  {/* name */ "core_4_qual_control", /* address */ 0x4410e194, /* default */ 0x00010000, /* description */ "Data qualifier control\n"}, 
  {/* name */ "core_4_status", /* address */ 0x4410e198, /* default */ 0x00000000, /* description */ "Core 4 status\n"}, 
  {/* name */ "core_4_addr", /* address */ 0x4410e19c, /* default */ 0x00000000, /* description */ "Core 4 address status\n"}, 
  {/* name */ "core_4_num_data", /* address */ 0x4410e1a0, /* default */ 0x00000000, /* description */ "Core 4 address status\n"}, 
  {/* name */ "core_4_rdata", /* address */ 0x4410e1b0, /* default */ 0x00000000, /* description */ "Core 4 read data\n"}
};

field_const_t field_const_dbgcapture_reg__intr_status[]  = {
  {/* name */ "mem_wr_wrap", /* range */ "[4:0]", /* default */ "0x0", /* access */ "read-only", /* description */ "Read operation done\n"}, 
  {/* name */ "triggered", /* range */ "[9:5]", /* default */ "0x0", /* access */ "read-only", /* description */ "program operation done\n"}, 
  {/* name */ "dummy_field", /* range */ "[15:10]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_dbgcapture_reg__intr_mask_status[]  = {
  {/* name */ "mem_wr_wrap", /* range */ "[4:0]", /* default */ "0x0", /* access */ "read-only", /* description */ "Read operation done\n"}, 
  {/* name */ "triggered", /* range */ "[9:5]", /* default */ "0x0", /* access */ "read-only", /* description */ "program operation done\n"}, 
  {/* name */ "dummy_field", /* range */ "[15:10]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_dbgcapture_reg__intr_clr[]  = {
  {/* name */ "mem_wr_wrap", /* range */ "[4:0]", /* default */ "0x0", /* access */ "read-write", /* description */ "Read operation done\n"}, 
  {/* name */ "triggered", /* range */ "[9:5]", /* default */ "0x0", /* access */ "read-write", /* description */ "program operation done\n"}, 
  {/* name */ "dummy_field", /* range */ "[15:10]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_dbgcapture_reg__intr_set[]  = {
  {/* name */ "mem_wr_wrap", /* range */ "[4:0]", /* default */ "0x0", /* access */ "read-write", /* description */ "Read operation done\n"}, 
  {/* name */ "triggered", /* range */ "[9:5]", /* default */ "0x0", /* access */ "read-write", /* description */ "program operation done\n"}, 
  {/* name */ "dummy_field", /* range */ "[15:10]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_dbgcapture_reg__intr_mask_set[]  = {
  {/* name */ "mem_wr_wrap", /* range */ "[4:0]", /* default */ "0x0", /* access */ "read-write", /* description */ "Read operation done\n"}, 
  {/* name */ "triggered", /* range */ "[9:5]", /* default */ "0x0", /* access */ "read-write", /* description */ "program operation done\n"}, 
  {/* name */ "dummy_field", /* range */ "[15:10]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_dbgcapture_reg__intr_mask_clr[]  = {
  {/* name */ "mem_wr_wrap", /* range */ "[4:0]", /* default */ "0x0", /* access */ "read-write", /* description */ "Read operation done\n"}, 
  {/* name */ "triggered", /* range */ "[9:5]", /* default */ "0x0", /* access */ "read-write", /* description */ "program operation done\n"}, 
  {/* name */ "dummy_field", /* range */ "[15:10]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_dbgcapture_reg__misc_ctrl[]  = {
  {/* name */ "ctl_dbcapture_en", /* range */ "[0:0]", /* default */ "0x0", /* access */ "read-write", /* description */ "Enable the block\n"}, 
  {/* name */ "ctl_rst_intrctrl", /* range */ "[1:1]", /* default */ "0x0", /* access */ "read-write", /* description */ "Enable the block\n"}, 
  {/* name */ "ctl_core_en", /* range */ "[9:4]", /* default */ "0x0", /* access */ "read-write", /* description */ "Enable each core\n"}, 
  {/* name */ "ctl_core_reset", /* range */ "[17:12]", /* default */ "0x3f", /* access */ "read-write", /* description */ "Reset each core\n"}, 
  {/* name */ "dummy_field", /* range */ "[23:18]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_dbgcapture_reg__misc_ctrl_start_stop[]  = {
  {/* name */ "ctl_core_start", /* range */ "[4:0]", /* default */ "0x0", /* access */ "read-write", /* description */ "Enable the block\n"}, 
  {/* name */ "ctl_core_force_trigger", /* range */ "[20:16]", /* default */ "0x0", /* access */ "read-write", /* description */ "Enable the block\n"}, 
  {/* name */ "dummy_field", /* range */ "[23:21]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_dbgcapture_reg__start_ctrl[]  = {
  {/* name */ "ctl_htransi_qualif_val", /* range */ "[1:0]", /* default */ "0x2", /* access */ "read-write", /* description */ "HTRANSI value for qualifier \n"}, 
  {/* name */ "ctl_htransd_qualif_val", /* range */ "[5:4]", /* default */ "0x2", /* access */ "read-write", /* description */ "HTRANSD value for qualifier \n"}, 
  {/* name */ "ctl_htranss_qualif_val", /* range */ "[9:8]", /* default */ "0x2", /* access */ "read-write", /* description */ "HTRANSS value for qualifier \n"}, 
  {/* name */ "dummy_field", /* range */ "[15:10]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_dbgcapture_reg__core_0_trig_sel_0[]  = {
  {/* name */ "sel_0", /* range */ "[2:0]", /* default */ "0x0", /* access */ "read-write", /* description */ "Trigger selection 0\n"}, 
  {/* name */ "sel_1", /* range */ "[6:4]", /* default */ "0x0", /* access */ "read-write", /* description */ "Trigger selection 1\n"}, 
  {/* name */ "sel_2", /* range */ "[10:8]", /* default */ "0x0", /* access */ "read-write", /* description */ "Trigger selection 2\n"}, 
  {/* name */ "sel_3", /* range */ "[14:12]", /* default */ "0x0", /* access */ "read-write", /* description */ "Trigger selection 3\n"}, 
  {/* name */ "sel_4", /* range */ "[18:16]", /* default */ "0x0", /* access */ "read-write", /* description */ "Trigger selection 4\n"}, 
  {/* name */ "dummy_field", /* range */ "[23:19]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_dbgcapture_reg__core_0_trig_sel_1[]  = {
  {/* name */ "sel_5", /* range */ "[2:0]", /* default */ "0x0", /* access */ "read-write", /* description */ "Trigger selection 5\n"}, 
  {/* name */ "sel_6", /* range */ "[6:4]", /* default */ "0x0", /* access */ "read-write", /* description */ "Trigger selection 6\n"}, 
  {/* name */ "sel_7", /* range */ "[10:8]", /* default */ "0x0", /* access */ "read-write", /* description */ "Trigger selection 7\n"}, 
  {/* name */ "sel_8", /* range */ "[14:12]", /* default */ "0x0", /* access */ "read-write", /* description */ "Trigger selection 8\n"}, 
  {/* name */ "sel_9", /* range */ "[18:16]", /* default */ "0x0", /* access */ "read-write", /* description */ "Trigger selection 9\n"}, 
  {/* name */ "dummy_field", /* range */ "[23:19]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_dbgcapture_reg__core_0_trig_cond[]  = {
  {/* name */ "val", /* range */ "[31:0]", /* default */ "0x0", /* access */ "read-write", /* description */ "value\n"}
};
field_const_t field_const_dbgcapture_reg__core_0_trig_mask[]  = {
  {/* name */ "val", /* range */ "[31:0]", /* default */ "0x0", /* access */ "read-write", /* description */ "value\n"}
};
field_const_t field_const_dbgcapture_reg__core_0_data_src_sel[]  = {
  {/* name */ "val", /* range */ "[3:0]", /* default */ "0x0", /* access */ "read-write", /* description */ "value\n"}, 
  {/* name */ "dummy_field", /* range */ "[7:4]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_dbgcapture_reg__core_0_qual_control[]  = {
  {/* name */ "qual_sel", /* range */ "[8:0]", /* default */ "0x0", /* access */ "read-write", /* description */ "enable which qualifier\n"}, 
  {/* name */ "qual_or0and1", /* range */ "[12:12]", /* default */ "0x0", /* access */ "read-write", /* description */ "Multiple qualifier operation\n"}, 
  {/* name */ "qual_force", /* range */ "[16:16]", /* default */ "0x1", /* access */ "read-write", /* description */ "Force storing all values\n"}, 
  {/* name */ "dummy_field", /* range */ "[23:17]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_dbgcapture_reg__core_0_status[]  = {
  {/* name */ "state", /* range */ "[1:0]", /* default */ "0x0", /* access */ "read-only", /* description */ "Current status\n"}, 
  {/* name */ "read_data_valid", /* range */ "[4:4]", /* default */ "0x0", /* access */ "read-only", /* description */ "Read data ready for read\n"}, 
  {/* name */ "dummy_field", /* range */ "[7:5]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_dbgcapture_reg__core_0_addr[]  = {
  {/* name */ "nxt_wr_addr", /* range */ "[15:0]", /* default */ "0x0", /* access */ "read-only", /* description */ "Next write address\n"}, 
  {/* name */ "last_rd_addr", /* range */ "[31:16]", /* default */ "0x0", /* access */ "read-only", /* description */ "Last read address\n"}
};
field_const_t field_const_dbgcapture_reg__core_0_num_data[]  = {
  {/* name */ "num_data", /* range */ "[15:0]", /* default */ "0x0", /* access */ "read-only", /* description */ "Number of data available. Ceiling at memory size\n"}
};
field_const_t field_const_dbgcapture_reg__core_0_rdata[]  = {
  {/* name */ "data", /* range */ "[31:0]", /* default */ "0x0", /* access */ "read-only", /* description */ "Read data. Read of this register will automatically move to next address\n"}
};
field_const_t field_const_dbgcapture_reg__core_1_trig_sel_0[]  = {
  {/* name */ "sel_0", /* range */ "[2:0]", /* default */ "0x0", /* access */ "read-write", /* description */ "Trigger selection 0\n"}, 
  {/* name */ "sel_1", /* range */ "[6:4]", /* default */ "0x0", /* access */ "read-write", /* description */ "Trigger selection 1\n"}, 
  {/* name */ "sel_2", /* range */ "[10:8]", /* default */ "0x0", /* access */ "read-write", /* description */ "Trigger selection 2\n"}, 
  {/* name */ "sel_3", /* range */ "[14:12]", /* default */ "0x0", /* access */ "read-write", /* description */ "Trigger selection 3\n"}, 
  {/* name */ "sel_4", /* range */ "[18:16]", /* default */ "0x0", /* access */ "read-write", /* description */ "Trigger selection 4\n"}, 
  {/* name */ "dummy_field", /* range */ "[23:19]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_dbgcapture_reg__core_1_trig_sel_1[]  = {
  {/* name */ "sel_5", /* range */ "[2:0]", /* default */ "0x0", /* access */ "read-write", /* description */ "Trigger selection 5\n"}, 
  {/* name */ "sel_6", /* range */ "[6:4]", /* default */ "0x0", /* access */ "read-write", /* description */ "Trigger selection 6\n"}, 
  {/* name */ "sel_7", /* range */ "[10:8]", /* default */ "0x0", /* access */ "read-write", /* description */ "Trigger selection 7\n"}, 
  {/* name */ "sel_8", /* range */ "[14:12]", /* default */ "0x0", /* access */ "read-write", /* description */ "Trigger selection 8\n"}, 
  {/* name */ "sel_9", /* range */ "[18:16]", /* default */ "0x0", /* access */ "read-write", /* description */ "Trigger selection 9\n"}, 
  {/* name */ "dummy_field", /* range */ "[23:19]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_dbgcapture_reg__core_1_trig_cond[]  = {
  {/* name */ "val", /* range */ "[31:0]", /* default */ "0x0", /* access */ "read-write", /* description */ "value\n"}
};
field_const_t field_const_dbgcapture_reg__core_1_trig_mask[]  = {
  {/* name */ "val", /* range */ "[31:0]", /* default */ "0x0", /* access */ "read-write", /* description */ "value\n"}
};
field_const_t field_const_dbgcapture_reg__core_1_data_src_sel[]  = {
  {/* name */ "val", /* range */ "[3:0]", /* default */ "0x0", /* access */ "read-write", /* description */ "value\n"}, 
  {/* name */ "dummy_field", /* range */ "[7:4]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_dbgcapture_reg__core_1_qual_control[]  = {
  {/* name */ "qual_sel", /* range */ "[8:0]", /* default */ "0x0", /* access */ "read-write", /* description */ "enable which qualifier\n"}, 
  {/* name */ "qual_or0and1", /* range */ "[12:12]", /* default */ "0x0", /* access */ "read-write", /* description */ "Multiple qualifier operation\n"}, 
  {/* name */ "qual_force", /* range */ "[16:16]", /* default */ "0x1", /* access */ "read-write", /* description */ "Force storing all values\n"}, 
  {/* name */ "dummy_field", /* range */ "[23:17]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_dbgcapture_reg__core_1_status[]  = {
  {/* name */ "state", /* range */ "[1:0]", /* default */ "0x0", /* access */ "read-only", /* description */ "Current status\n"}, 
  {/* name */ "read_data_valid", /* range */ "[4:4]", /* default */ "0x0", /* access */ "read-only", /* description */ "Read data ready for read\n"}, 
  {/* name */ "dummy_field", /* range */ "[7:5]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_dbgcapture_reg__core_1_addr[]  = {
  {/* name */ "nxt_wr_addr", /* range */ "[15:0]", /* default */ "0x0", /* access */ "read-only", /* description */ "Next write address\n"}, 
  {/* name */ "last_rd_addr", /* range */ "[31:16]", /* default */ "0x0", /* access */ "read-only", /* description */ "Last read address\n"}
};
field_const_t field_const_dbgcapture_reg__core_1_num_data[]  = {
  {/* name */ "num_data", /* range */ "[15:0]", /* default */ "0x0", /* access */ "read-only", /* description */ "Number of data available. Ceiling at memory size\n"}
};
field_const_t field_const_dbgcapture_reg__core_1_rdata[]  = {
  {/* name */ "data", /* range */ "[31:0]", /* default */ "0x0", /* access */ "read-only", /* description */ "Read data. Read of this register will automatically move to next address\n"}
};
field_const_t field_const_dbgcapture_reg__core_2_trig_sel_0[]  = {
  {/* name */ "sel_0", /* range */ "[2:0]", /* default */ "0x0", /* access */ "read-write", /* description */ "Trigger selection 0\n"}, 
  {/* name */ "sel_1", /* range */ "[6:4]", /* default */ "0x0", /* access */ "read-write", /* description */ "Trigger selection 1\n"}, 
  {/* name */ "sel_2", /* range */ "[10:8]", /* default */ "0x0", /* access */ "read-write", /* description */ "Trigger selection 2\n"}, 
  {/* name */ "sel_3", /* range */ "[14:12]", /* default */ "0x0", /* access */ "read-write", /* description */ "Trigger selection 3\n"}, 
  {/* name */ "sel_4", /* range */ "[18:16]", /* default */ "0x0", /* access */ "read-write", /* description */ "Trigger selection 4\n"}, 
  {/* name */ "dummy_field", /* range */ "[23:19]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_dbgcapture_reg__core_2_trig_sel_1[]  = {
  {/* name */ "sel_5", /* range */ "[2:0]", /* default */ "0x0", /* access */ "read-write", /* description */ "Trigger selection 5\n"}, 
  {/* name */ "sel_6", /* range */ "[6:4]", /* default */ "0x0", /* access */ "read-write", /* description */ "Trigger selection 6\n"}, 
  {/* name */ "sel_7", /* range */ "[10:8]", /* default */ "0x0", /* access */ "read-write", /* description */ "Trigger selection 7\n"}, 
  {/* name */ "sel_8", /* range */ "[14:12]", /* default */ "0x0", /* access */ "read-write", /* description */ "Trigger selection 8\n"}, 
  {/* name */ "sel_9", /* range */ "[18:16]", /* default */ "0x0", /* access */ "read-write", /* description */ "Trigger selection 9\n"}, 
  {/* name */ "dummy_field", /* range */ "[23:19]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_dbgcapture_reg__core_2_trig_cond[]  = {
  {/* name */ "val", /* range */ "[31:0]", /* default */ "0x0", /* access */ "read-write", /* description */ "value\n"}
};
field_const_t field_const_dbgcapture_reg__core_2_trig_mask[]  = {
  {/* name */ "val", /* range */ "[31:0]", /* default */ "0x0", /* access */ "read-write", /* description */ "value\n"}
};
field_const_t field_const_dbgcapture_reg__core_2_data_src_sel[]  = {
  {/* name */ "val", /* range */ "[3:0]", /* default */ "0x0", /* access */ "read-write", /* description */ "value\n"}, 
  {/* name */ "dummy_field", /* range */ "[7:4]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_dbgcapture_reg__core_2_qual_control[]  = {
  {/* name */ "qual_sel", /* range */ "[8:0]", /* default */ "0x0", /* access */ "read-write", /* description */ "enable which qualifier\n"}, 
  {/* name */ "qual_or0and1", /* range */ "[12:12]", /* default */ "0x0", /* access */ "read-write", /* description */ "Multiple qualifier operation\n"}, 
  {/* name */ "qual_force", /* range */ "[16:16]", /* default */ "0x1", /* access */ "read-write", /* description */ "Force storing all values\n"}, 
  {/* name */ "dummy_field", /* range */ "[23:17]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_dbgcapture_reg__core_2_status[]  = {
  {/* name */ "state", /* range */ "[1:0]", /* default */ "0x0", /* access */ "read-only", /* description */ "Current status\n"}, 
  {/* name */ "read_data_valid", /* range */ "[4:4]", /* default */ "0x0", /* access */ "read-only", /* description */ "Read data ready for read\n"}, 
  {/* name */ "dummy_field", /* range */ "[7:5]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_dbgcapture_reg__core_2_addr[]  = {
  {/* name */ "nxt_wr_addr", /* range */ "[15:0]", /* default */ "0x0", /* access */ "read-only", /* description */ "Next write address\n"}, 
  {/* name */ "last_rd_addr", /* range */ "[31:16]", /* default */ "0x0", /* access */ "read-only", /* description */ "Last read address\n"}
};
field_const_t field_const_dbgcapture_reg__core_2_num_data[]  = {
  {/* name */ "num_data", /* range */ "[15:0]", /* default */ "0x0", /* access */ "read-only", /* description */ "Number of data available. Ceiling at memory size\n"}
};
field_const_t field_const_dbgcapture_reg__core_2_rdata[]  = {
  {/* name */ "data", /* range */ "[31:0]", /* default */ "0x0", /* access */ "read-only", /* description */ "Read data. Read of this register will automatically move to next address\n"}
};
field_const_t field_const_dbgcapture_reg__core_3_trig_sel_0[]  = {
  {/* name */ "sel_0", /* range */ "[2:0]", /* default */ "0x0", /* access */ "read-write", /* description */ "Trigger selection 0\n"}, 
  {/* name */ "sel_1", /* range */ "[6:4]", /* default */ "0x0", /* access */ "read-write", /* description */ "Trigger selection 1\n"}, 
  {/* name */ "sel_2", /* range */ "[10:8]", /* default */ "0x0", /* access */ "read-write", /* description */ "Trigger selection 2\n"}, 
  {/* name */ "sel_3", /* range */ "[14:12]", /* default */ "0x0", /* access */ "read-write", /* description */ "Trigger selection 3\n"}, 
  {/* name */ "sel_4", /* range */ "[18:16]", /* default */ "0x0", /* access */ "read-write", /* description */ "Trigger selection 4\n"}, 
  {/* name */ "dummy_field", /* range */ "[23:19]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_dbgcapture_reg__core_3_trig_sel_1[]  = {
  {/* name */ "sel_5", /* range */ "[2:0]", /* default */ "0x0", /* access */ "read-write", /* description */ "Trigger selection 5\n"}, 
  {/* name */ "sel_6", /* range */ "[6:4]", /* default */ "0x0", /* access */ "read-write", /* description */ "Trigger selection 6\n"}, 
  {/* name */ "sel_7", /* range */ "[10:8]", /* default */ "0x0", /* access */ "read-write", /* description */ "Trigger selection 7\n"}, 
  {/* name */ "sel_8", /* range */ "[14:12]", /* default */ "0x0", /* access */ "read-write", /* description */ "Trigger selection 8\n"}, 
  {/* name */ "sel_9", /* range */ "[18:16]", /* default */ "0x0", /* access */ "read-write", /* description */ "Trigger selection 9\n"}, 
  {/* name */ "dummy_field", /* range */ "[23:19]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_dbgcapture_reg__core_3_trig_cond[]  = {
  {/* name */ "val", /* range */ "[31:0]", /* default */ "0x0", /* access */ "read-write", /* description */ "value\n"}
};
field_const_t field_const_dbgcapture_reg__core_3_trig_mask[]  = {
  {/* name */ "val", /* range */ "[31:0]", /* default */ "0x0", /* access */ "read-write", /* description */ "value\n"}
};
field_const_t field_const_dbgcapture_reg__core_3_data_src_sel[]  = {
  {/* name */ "val", /* range */ "[3:0]", /* default */ "0x0", /* access */ "read-write", /* description */ "value\n"}, 
  {/* name */ "dummy_field", /* range */ "[7:4]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_dbgcapture_reg__core_3_qual_control[]  = {
  {/* name */ "qual_sel", /* range */ "[8:0]", /* default */ "0x0", /* access */ "read-write", /* description */ "enable which qualifier\n"}, 
  {/* name */ "qual_or0and1", /* range */ "[12:12]", /* default */ "0x0", /* access */ "read-write", /* description */ "Multiple qualifier operation\n"}, 
  {/* name */ "qual_force", /* range */ "[16:16]", /* default */ "0x1", /* access */ "read-write", /* description */ "Force storing all values\n"}, 
  {/* name */ "dummy_field", /* range */ "[23:17]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_dbgcapture_reg__core_3_status[]  = {
  {/* name */ "state", /* range */ "[1:0]", /* default */ "0x0", /* access */ "read-only", /* description */ "Current status\n"}, 
  {/* name */ "read_data_valid", /* range */ "[4:4]", /* default */ "0x0", /* access */ "read-only", /* description */ "Read data ready for read\n"}, 
  {/* name */ "dummy_field", /* range */ "[7:5]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_dbgcapture_reg__core_3_addr[]  = {
  {/* name */ "nxt_wr_addr", /* range */ "[15:0]", /* default */ "0x0", /* access */ "read-only", /* description */ "Next write address\n"}, 
  {/* name */ "last_rd_addr", /* range */ "[31:16]", /* default */ "0x0", /* access */ "read-only", /* description */ "Last read address\n"}
};
field_const_t field_const_dbgcapture_reg__core_3_num_data[]  = {
  {/* name */ "num_data", /* range */ "[15:0]", /* default */ "0x0", /* access */ "read-only", /* description */ "Number of data available. Ceiling at memory size\n"}
};
field_const_t field_const_dbgcapture_reg__core_3_rdata[]  = {
  {/* name */ "data", /* range */ "[31:0]", /* default */ "0x0", /* access */ "read-only", /* description */ "Read data. Read of this register will automatically move to next address\n"}
};
field_const_t field_const_dbgcapture_reg__core_4_trig_sel_0[]  = {
  {/* name */ "sel_0", /* range */ "[2:0]", /* default */ "0x0", /* access */ "read-write", /* description */ "Trigger selection 0\n"}, 
  {/* name */ "sel_1", /* range */ "[6:4]", /* default */ "0x0", /* access */ "read-write", /* description */ "Trigger selection 1\n"}, 
  {/* name */ "sel_2", /* range */ "[10:8]", /* default */ "0x0", /* access */ "read-write", /* description */ "Trigger selection 2\n"}, 
  {/* name */ "sel_3", /* range */ "[14:12]", /* default */ "0x0", /* access */ "read-write", /* description */ "Trigger selection 3\n"}, 
  {/* name */ "sel_4", /* range */ "[18:16]", /* default */ "0x0", /* access */ "read-write", /* description */ "Trigger selection 4\n"}, 
  {/* name */ "dummy_field", /* range */ "[23:19]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_dbgcapture_reg__core_4_trig_sel_1[]  = {
  {/* name */ "sel_5", /* range */ "[2:0]", /* default */ "0x0", /* access */ "read-write", /* description */ "Trigger selection 5\n"}, 
  {/* name */ "sel_6", /* range */ "[6:4]", /* default */ "0x0", /* access */ "read-write", /* description */ "Trigger selection 6\n"}, 
  {/* name */ "sel_7", /* range */ "[10:8]", /* default */ "0x0", /* access */ "read-write", /* description */ "Trigger selection 7\n"}, 
  {/* name */ "sel_8", /* range */ "[14:12]", /* default */ "0x0", /* access */ "read-write", /* description */ "Trigger selection 8\n"}, 
  {/* name */ "sel_9", /* range */ "[18:16]", /* default */ "0x0", /* access */ "read-write", /* description */ "Trigger selection 9\n"}, 
  {/* name */ "dummy_field", /* range */ "[23:19]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_dbgcapture_reg__core_4_trig_cond[]  = {
  {/* name */ "val", /* range */ "[31:0]", /* default */ "0x0", /* access */ "read-write", /* description */ "value\n"}
};
field_const_t field_const_dbgcapture_reg__core_4_trig_mask[]  = {
  {/* name */ "val", /* range */ "[31:0]", /* default */ "0x0", /* access */ "read-write", /* description */ "value\n"}
};
field_const_t field_const_dbgcapture_reg__core_4_data_src_sel[]  = {
  {/* name */ "val", /* range */ "[3:0]", /* default */ "0x0", /* access */ "read-write", /* description */ "value\n"}, 
  {/* name */ "dummy_field", /* range */ "[7:4]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_dbgcapture_reg__core_4_qual_control[]  = {
  {/* name */ "qual_sel", /* range */ "[8:0]", /* default */ "0x0", /* access */ "read-write", /* description */ "enable which qualifier\n"}, 
  {/* name */ "qual_or0and1", /* range */ "[12:12]", /* default */ "0x0", /* access */ "read-write", /* description */ "Multiple qualifier operation\n"}, 
  {/* name */ "qual_force", /* range */ "[16:16]", /* default */ "0x1", /* access */ "read-write", /* description */ "Force storing all values\n"}, 
  {/* name */ "dummy_field", /* range */ "[23:17]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_dbgcapture_reg__core_4_status[]  = {
  {/* name */ "state", /* range */ "[1:0]", /* default */ "0x0", /* access */ "read-only", /* description */ "Current status\n"}, 
  {/* name */ "read_data_valid", /* range */ "[4:4]", /* default */ "0x0", /* access */ "read-only", /* description */ "Read data ready for read\n"}, 
  {/* name */ "dummy_field", /* range */ "[7:5]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_dbgcapture_reg__core_4_addr[]  = {
  {/* name */ "nxt_wr_addr", /* range */ "[15:0]", /* default */ "0x0", /* access */ "read-only", /* description */ "Next write address\n"}, 
  {/* name */ "last_rd_addr", /* range */ "[31:16]", /* default */ "0x0", /* access */ "read-only", /* description */ "Last read address\n"}
};
field_const_t field_const_dbgcapture_reg__core_4_num_data[]  = {
  {/* name */ "num_data", /* range */ "[15:0]", /* default */ "0x0", /* access */ "read-only", /* description */ "Number of data available. Ceiling at memory size\n"}
};
field_const_t field_const_dbgcapture_reg__core_4_rdata[]  = {
  {/* name */ "data", /* range */ "[31:0]", /* default */ "0x0", /* access */ "read-only", /* description */ "Read data. Read of this register will automatically move to next address\n"}
};

field_const_array_t reg_pnt_list__dbgcapture_reg[NUM_REGS__DBGCAPTURE_REG] = {
  { /* pfield */ field_const_dbgcapture_reg__intr_status, /* size */ 3}, 
  { /* pfield */ field_const_dbgcapture_reg__intr_mask_status, /* size */ 3}, 
  { /* pfield */ field_const_dbgcapture_reg__intr_clr, /* size */ 3}, 
  { /* pfield */ field_const_dbgcapture_reg__intr_set, /* size */ 3}, 
  { /* pfield */ field_const_dbgcapture_reg__intr_mask_set, /* size */ 3}, 
  { /* pfield */ field_const_dbgcapture_reg__intr_mask_clr, /* size */ 3}, 
  { /* pfield */ field_const_dbgcapture_reg__misc_ctrl, /* size */ 5}, 
  { /* pfield */ field_const_dbgcapture_reg__misc_ctrl_start_stop, /* size */ 3}, 
  { /* pfield */ field_const_dbgcapture_reg__start_ctrl, /* size */ 4}, 
  { /* pfield */ field_const_dbgcapture_reg__core_0_trig_sel_0, /* size */ 6}, 
  { /* pfield */ field_const_dbgcapture_reg__core_0_trig_sel_1, /* size */ 6}, 
  { /* pfield */ field_const_dbgcapture_reg__core_0_trig_cond, /* size */ 1}, 
  { /* pfield */ field_const_dbgcapture_reg__core_0_trig_mask, /* size */ 1}, 
  { /* pfield */ field_const_dbgcapture_reg__core_0_data_src_sel, /* size */ 2}, 
  { /* pfield */ field_const_dbgcapture_reg__core_0_qual_control, /* size */ 4}, 
  { /* pfield */ field_const_dbgcapture_reg__core_0_status, /* size */ 3}, 
  { /* pfield */ field_const_dbgcapture_reg__core_0_addr, /* size */ 2}, 
  { /* pfield */ field_const_dbgcapture_reg__core_0_num_data, /* size */ 1}, 
  { /* pfield */ field_const_dbgcapture_reg__core_0_rdata, /* size */ 1}, 
  { /* pfield */ field_const_dbgcapture_reg__core_1_trig_sel_0, /* size */ 6}, 
  { /* pfield */ field_const_dbgcapture_reg__core_1_trig_sel_1, /* size */ 6}, 
  { /* pfield */ field_const_dbgcapture_reg__core_1_trig_cond, /* size */ 1}, 
  { /* pfield */ field_const_dbgcapture_reg__core_1_trig_mask, /* size */ 1}, 
  { /* pfield */ field_const_dbgcapture_reg__core_1_data_src_sel, /* size */ 2}, 
  { /* pfield */ field_const_dbgcapture_reg__core_1_qual_control, /* size */ 4}, 
  { /* pfield */ field_const_dbgcapture_reg__core_1_status, /* size */ 3}, 
  { /* pfield */ field_const_dbgcapture_reg__core_1_addr, /* size */ 2}, 
  { /* pfield */ field_const_dbgcapture_reg__core_1_num_data, /* size */ 1}, 
  { /* pfield */ field_const_dbgcapture_reg__core_1_rdata, /* size */ 1}, 
  { /* pfield */ field_const_dbgcapture_reg__core_2_trig_sel_0, /* size */ 6}, 
  { /* pfield */ field_const_dbgcapture_reg__core_2_trig_sel_1, /* size */ 6}, 
  { /* pfield */ field_const_dbgcapture_reg__core_2_trig_cond, /* size */ 1}, 
  { /* pfield */ field_const_dbgcapture_reg__core_2_trig_mask, /* size */ 1}, 
  { /* pfield */ field_const_dbgcapture_reg__core_2_data_src_sel, /* size */ 2}, 
  { /* pfield */ field_const_dbgcapture_reg__core_2_qual_control, /* size */ 4}, 
  { /* pfield */ field_const_dbgcapture_reg__core_2_status, /* size */ 3}, 
  { /* pfield */ field_const_dbgcapture_reg__core_2_addr, /* size */ 2}, 
  { /* pfield */ field_const_dbgcapture_reg__core_2_num_data, /* size */ 1}, 
  { /* pfield */ field_const_dbgcapture_reg__core_2_rdata, /* size */ 1}, 
  { /* pfield */ field_const_dbgcapture_reg__core_3_trig_sel_0, /* size */ 6}, 
  { /* pfield */ field_const_dbgcapture_reg__core_3_trig_sel_1, /* size */ 6}, 
  { /* pfield */ field_const_dbgcapture_reg__core_3_trig_cond, /* size */ 1}, 
  { /* pfield */ field_const_dbgcapture_reg__core_3_trig_mask, /* size */ 1}, 
  { /* pfield */ field_const_dbgcapture_reg__core_3_data_src_sel, /* size */ 2}, 
  { /* pfield */ field_const_dbgcapture_reg__core_3_qual_control, /* size */ 4}, 
  { /* pfield */ field_const_dbgcapture_reg__core_3_status, /* size */ 3}, 
  { /* pfield */ field_const_dbgcapture_reg__core_3_addr, /* size */ 2}, 
  { /* pfield */ field_const_dbgcapture_reg__core_3_num_data, /* size */ 1}, 
  { /* pfield */ field_const_dbgcapture_reg__core_3_rdata, /* size */ 1}, 
  { /* pfield */ field_const_dbgcapture_reg__core_4_trig_sel_0, /* size */ 6}, 
  { /* pfield */ field_const_dbgcapture_reg__core_4_trig_sel_1, /* size */ 6}, 
  { /* pfield */ field_const_dbgcapture_reg__core_4_trig_cond, /* size */ 1}, 
  { /* pfield */ field_const_dbgcapture_reg__core_4_trig_mask, /* size */ 1}, 
  { /* pfield */ field_const_dbgcapture_reg__core_4_data_src_sel, /* size */ 2}, 
  { /* pfield */ field_const_dbgcapture_reg__core_4_qual_control, /* size */ 4}, 
  { /* pfield */ field_const_dbgcapture_reg__core_4_status, /* size */ 3}, 
  { /* pfield */ field_const_dbgcapture_reg__core_4_addr, /* size */ 2}, 
  { /* pfield */ field_const_dbgcapture_reg__core_4_num_data, /* size */ 1}, 
  { /* pfield */ field_const_dbgcapture_reg__core_4_rdata, /* size */ 1}
};
