/////////////////////////////////////////////////////////////////////////////////
// This file has been automatically generated by register_slave.pl version dc9b7d3
/////////////////////////////////////////////////////////////////////////////////

// type declaration
#ifndef __REG_CONST_T
#define __REG_CONST_T

#ifndef REG_CONST_NAME_STRING_MAX_LEN   
#define REG_CONST_NAME_STRING_MAX_LEN 64
#endif // REG_CONST_NAME_STRING_MAX_LEN
#ifndef REG_CONST_DESC_STRING_MAX_LEN
#define REG_CONST_DESC_STRING_MAX_LEN 512
#endif // REG_CONST_DESC_STRING_MAX_LEN
typedef struct {
	char name[REG_CONST_NAME_STRING_MAX_LEN];
	DWORD address;
	DWORD def;
	char desc[REG_CONST_DESC_STRING_MAX_LEN];
} reg_const_t;
typedef struct {
	char name[REG_CONST_NAME_STRING_MAX_LEN];
	char range[32];
	char def[32];
	char access[32];
	char desc[REG_CONST_DESC_STRING_MAX_LEN];
} field_const_t;
typedef struct {
	field_const_t *pfield;
	DWORD size;
} field_const_array_t;
#endif // __REG_CONST_T

#define NUM_REGS__EFUSECTRL_REG  34
/* { reg_const_efusectrl_reg, 34, "efusectrl_reg"},  */ 
static reg_const_t reg_const_efusectrl_reg[NUM_REGS__EFUSECTRL_REG] = {
  {/* name */ "intr_status", /* address */ 0x44104000, /* default */ 0x00000000, /* description */ "Interrupt status register bits. \n"}, 
  {/* name */ "intr_mask_status", /* address */ 0x44104004, /* default */ 0x00000000, /* description */ "Interrupt mask status register\n"}, 
  {/* name */ "intr_clr", /* address */ 0x44104008, /* default */ 0x00000000, /* description */ "Clear interrupt status\n"}, 
  {/* name */ "intr_set", /* address */ 0x4410400c, /* default */ 0x00000000, /* description */ "Set interrupt status\n"}, 
  {/* name */ "intr_mask_set", /* address */ 0x44104010, /* default */ 0x00000000, /* description */ "Set interrupt mask\n"}, 
  {/* name */ "intr_mask_clr", /* address */ 0x44104014, /* default */ 0x00000000, /* description */ "Set interrupt mask\n"}, 
  {/* name */ "misc_ctrl_0", /* address */ 0x44104020, /* default */ 0x00000000, /* description */ "Basic control register\n"}, 
  {/* name */ "misc_sts_0", /* address */ 0x44104028, /* default */ 0x00000000, /* description */ "Basic control register\n"}, 
  {/* name */ "init_rd_value_0_0", /* address */ 0x44104030, /* default */ 0x00000000, /* description */ "Basic control register\n"}, 
  {/* name */ "init_rd_value_0_1", /* address */ 0x44104034, /* default */ 0x00000000, /* description */ "Basic control register\n"}, 
  {/* name */ "read_ctrl_0", /* address */ 0x44104040, /* default */ 0x00000000, /* description */ "Read operation control\n"}, 
  {/* name */ "read_val_0", /* address */ 0x44104044, /* default */ 0x00000000, /* description */ "Read data\n"}, 
  {/* name */ "prog_ctrl_0", /* address */ 0x44104050, /* default */ 0x00000000, /* description */ "Program operation control\n"}, 
  {/* name */ "counter_ctrl_0_0", /* address */ 0x44104060, /* default */ 0x01004010, /* description */ "counter control\n"}, 
  {/* name */ "counter_ctrl_0_1", /* address */ 0x44104064, /* default */ 0x01004010, /* description */ "counter control\n"}, 
  {/* name */ "counter_ctrl_0_2", /* address */ 0x44104068, /* default */ 0x00004010, /* description */ "counter control\n"}, 
  {/* name */ "misc_ctrl_1", /* address */ 0x441040a0, /* default */ 0x00000000, /* description */ "Basic control register\n"}, 
  {/* name */ "misc_sts_1", /* address */ 0x441040a8, /* default */ 0x00000000, /* description */ "Basic control register\n"}, 
  {/* name */ "init_rd_value_1_0", /* address */ 0x441040b0, /* default */ 0x00000000, /* description */ "Basic control register\n"}, 
  {/* name */ "init_rd_value_1_1", /* address */ 0x441040b4, /* default */ 0x00000000, /* description */ "Basic control register\n"}, 
  {/* name */ "read_ctrl_1", /* address */ 0x441040c0, /* default */ 0x00000000, /* description */ "Read operation control\n"}, 
  {/* name */ "read_val_1", /* address */ 0x441040c4, /* default */ 0x00000000, /* description */ "Read data\n"}, 
  {/* name */ "prog_ctrl_1", /* address */ 0x441040d0, /* default */ 0x00000000, /* description */ "Program operation control\n"}, 
  {/* name */ "counter_ctrl_1_0", /* address */ 0x441040e0, /* default */ 0x01004010, /* description */ "counter control\n"}, 
  {/* name */ "counter_ctrl_1_1", /* address */ 0x441040e4, /* default */ 0x01004010, /* description */ "counter control\n"}, 
  {/* name */ "counter_ctrl_1_2", /* address */ 0x441040e8, /* default */ 0x00004010, /* description */ "counter control\n"}, 
  {/* name */ "inplay_init_rd_val", /* address */ 0x44104100, /* default */ 0x00000000, /* description */ "Inplay (efuse controller 1) initial read value\n"}, 
  {/* name */ "qspi_pin_mux_sel", /* address */ 0x44104104, /* default */ 0x00000000, /* description */ "UUID 31:0\n"}, 
  {/* name */ "uuid0", /* address */ 0x44104110, /* default */ 0x00000000, /* description */ "UUID 31:0\n"}, 
  {/* name */ "uuid1", /* address */ 0x44104114, /* default */ 0x00000000, /* description */ "UUID 63:32\n"}, 
  {/* name */ "uuid2", /* address */ 0x44104118, /* default */ 0x00000000, /* description */ "UUID 95:64\n"}, 
  {/* name */ "uuid3", /* address */ 0x4410411c, /* default */ 0x00000000, /* description */ "UUID 127:96\n"}, 
  {/* name */ "customer_init_rd_value", /* address */ 0x44104140, /* default */ 0x00000000, /* description */ "Customer initial read value\n"}, 
  {/* name */ "customer_id", /* address */ 0x44104144, /* default */ 0x00000000, /* description */ "Customer initial read value\n"}
};

field_const_t field_const_efusectrl_reg__intr_status[]  = {
  {/* name */ "read_done_0", /* range */ "[0:0]", /* default */ "0x0", /* access */ "read-only", /* description */ "Read operation done\n"}, 
  {/* name */ "prog_done_0", /* range */ "[1:1]", /* default */ "0x0", /* access */ "read-only", /* description */ "program operation done\n"}, 
  {/* name */ "prog_blocked_0", /* range */ "[2:2]", /* default */ "0x0", /* access */ "read-only", /* description */ "program operation blocked\n"}, 
  {/* name */ "read_done_1", /* range */ "[3:3]", /* default */ "0x0", /* access */ "read-only", /* description */ "Read operation done\n"}, 
  {/* name */ "prog_done_1", /* range */ "[4:4]", /* default */ "0x0", /* access */ "read-only", /* description */ "program operation done\n"}, 
  {/* name */ "prog_blocked_1", /* range */ "[5:5]", /* default */ "0x0", /* access */ "read-only", /* description */ "program operation blocked\n"}, 
  {/* name */ "dummy_field", /* range */ "[7:6]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_efusectrl_reg__intr_mask_status[]  = {
  {/* name */ "read_done_0", /* range */ "[0:0]", /* default */ "0x0", /* access */ "read-only", /* description */ "Read operation done\n"}, 
  {/* name */ "prog_done_0", /* range */ "[1:1]", /* default */ "0x0", /* access */ "read-only", /* description */ "program operation done\n"}, 
  {/* name */ "prog_blocked_0", /* range */ "[2:2]", /* default */ "0x0", /* access */ "read-only", /* description */ "program operation blocked\n"}, 
  {/* name */ "read_done_1", /* range */ "[3:3]", /* default */ "0x0", /* access */ "read-only", /* description */ "Read operation done\n"}, 
  {/* name */ "prog_done_1", /* range */ "[4:4]", /* default */ "0x0", /* access */ "read-only", /* description */ "program operation done\n"}, 
  {/* name */ "prog_blocked_1", /* range */ "[5:5]", /* default */ "0x0", /* access */ "read-only", /* description */ "program operation blocked\n"}, 
  {/* name */ "dummy_field", /* range */ "[7:6]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_efusectrl_reg__intr_clr[]  = {
  {/* name */ "read_done_0", /* range */ "[0:0]", /* default */ "0x0", /* access */ "read-write", /* description */ "Read operation done\n"}, 
  {/* name */ "prog_done_0", /* range */ "[1:1]", /* default */ "0x0", /* access */ "read-write", /* description */ "program operation done\n"}, 
  {/* name */ "prog_blocked_0", /* range */ "[2:2]", /* default */ "0x0", /* access */ "read-write", /* description */ "program operation blocked\n"}, 
  {/* name */ "read_done_1", /* range */ "[3:3]", /* default */ "0x0", /* access */ "read-write", /* description */ "Read operation done\n"}, 
  {/* name */ "prog_done_1", /* range */ "[4:4]", /* default */ "0x0", /* access */ "read-write", /* description */ "program operation done\n"}, 
  {/* name */ "prog_blocked_1", /* range */ "[5:5]", /* default */ "0x0", /* access */ "read-write", /* description */ "program operation blocked\n"}, 
  {/* name */ "dummy_field", /* range */ "[7:6]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_efusectrl_reg__intr_set[]  = {
  {/* name */ "read_done_0", /* range */ "[0:0]", /* default */ "0x0", /* access */ "read-write", /* description */ "Read operation done\n"}, 
  {/* name */ "prog_done_0", /* range */ "[1:1]", /* default */ "0x0", /* access */ "read-write", /* description */ "program operation done\n"}, 
  {/* name */ "prog_blocked_0", /* range */ "[2:2]", /* default */ "0x0", /* access */ "read-write", /* description */ "program operation blocked\n"}, 
  {/* name */ "read_done_1", /* range */ "[3:3]", /* default */ "0x0", /* access */ "read-write", /* description */ "Read operation done\n"}, 
  {/* name */ "prog_done_1", /* range */ "[4:4]", /* default */ "0x0", /* access */ "read-write", /* description */ "program operation done\n"}, 
  {/* name */ "prog_blocked_1", /* range */ "[5:5]", /* default */ "0x0", /* access */ "read-write", /* description */ "program operation blocked\n"}, 
  {/* name */ "dummy_field", /* range */ "[7:6]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_efusectrl_reg__intr_mask_set[]  = {
  {/* name */ "read_done_0", /* range */ "[0:0]", /* default */ "0x0", /* access */ "read-write", /* description */ "Read operation done\n"}, 
  {/* name */ "prog_done_0", /* range */ "[1:1]", /* default */ "0x0", /* access */ "read-write", /* description */ "program operation done\n"}, 
  {/* name */ "prog_blocked_0", /* range */ "[2:2]", /* default */ "0x0", /* access */ "read-write", /* description */ "program operation blocked\n"}, 
  {/* name */ "read_done_1", /* range */ "[3:3]", /* default */ "0x0", /* access */ "read-write", /* description */ "Read operation done\n"}, 
  {/* name */ "prog_done_1", /* range */ "[4:4]", /* default */ "0x0", /* access */ "read-write", /* description */ "program operation done\n"}, 
  {/* name */ "prog_blocked_1", /* range */ "[5:5]", /* default */ "0x0", /* access */ "read-write", /* description */ "program operation blocked\n"}, 
  {/* name */ "dummy_field", /* range */ "[7:6]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_efusectrl_reg__intr_mask_clr[]  = {
  {/* name */ "read_done_0", /* range */ "[0:0]", /* default */ "0x0", /* access */ "read-write", /* description */ "Read operation done\n"}, 
  {/* name */ "prog_done_0", /* range */ "[1:1]", /* default */ "0x0", /* access */ "read-write", /* description */ "program operation done\n"}, 
  {/* name */ "prog_blocked_0", /* range */ "[2:2]", /* default */ "0x0", /* access */ "read-write", /* description */ "program operation blocked\n"}, 
  {/* name */ "read_done_1", /* range */ "[3:3]", /* default */ "0x0", /* access */ "read-write", /* description */ "Read operation done\n"}, 
  {/* name */ "prog_done_1", /* range */ "[4:4]", /* default */ "0x0", /* access */ "read-write", /* description */ "program operation done\n"}, 
  {/* name */ "prog_blocked_1", /* range */ "[5:5]", /* default */ "0x0", /* access */ "read-write", /* description */ "program operation blocked\n"}, 
  {/* name */ "dummy_field", /* range */ "[7:6]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_efusectrl_reg__misc_ctrl_0[]  = {
  {/* name */ "ctl_efuse_en_0", /* range */ "[0:0]", /* default */ "0x0", /* access */ "read-write", /* description */ "Enable efuse read/write\n"}, 
  {/* name */ "ctl_efuse_intr_clr_0", /* range */ "[1:1]", /* default */ "0x0", /* access */ "read-write", /* description */ "Enable efuse interrupt clear\n"}, 
  {/* name */ "ctl_efuse_prog_en_0", /* range */ "[4:4]", /* default */ "0x0", /* access */ "read-write", /* description */ "Enable programming\n"}, 
  {/* name */ "dummy_field", /* range */ "[7:5]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_efusectrl_reg__misc_sts_0[]  = {
  {/* name */ "sts_efuse_prog_blk_0", /* range */ "[0:0]", /* default */ "0x0", /* access */ "read-only", /* description */ "Efuse program blocked\n"}, 
  {/* name */ "sts_efuse_init_rd_byp_0", /* range */ "[20:20]", /* default */ "0x0", /* access */ "read-only", /* description */ "Efuse initial read bypassed\n"}, 
  {/* name */ "sts_efuse_curr_state_0", /* range */ "[27:24]", /* default */ "0x0", /* access */ "read-only", /* description */ "Efuse controller core current state\n"}, 
  {/* name */ "dummy_field", /* range */ "[31:28]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_efusectrl_reg__init_rd_value_0_0[]  = {
  {/* name */ "sts_efuse_init_rd_val_0_0", /* range */ "[31:0]", /* default */ "0x0", /* access */ "read-only", /* description */ "Efuse initial read value 0\n"}
};
field_const_t field_const_efusectrl_reg__init_rd_value_0_1[]  = {
  {/* name */ "sts_efuse_init_rd_val_0_1", /* range */ "[31:0]", /* default */ "0x0", /* access */ "read-only", /* description */ "Efuse initial read value 1\n"}
};
field_const_t field_const_efusectrl_reg__read_ctrl_0[]  = {
  {/* name */ "ctl_efuse_read_req_0", /* range */ "[0:0]", /* default */ "0x0", /* access */ "read-write", /* description */ "Efuse read req\n"}, 
  {/* name */ "ctl_efuse_read_addr_0", /* range */ "[8:4]", /* default */ "0x0", /* access */ "read-write", /* description */ "Efuse read adress\n"}, 
  {/* name */ "ctl_efuse_read_efuse_sel_0", /* range */ "[13:12]", /* default */ "0x0", /* access */ "read-write", /* description */ "Efuse selection\n"}, 
  {/* name */ "ctl_efuse_read_mode_0", /* range */ "[16:16]", /* default */ "0x0", /* access */ "read-write", /* description */ "Efuse read mode: 0 - half word, 1 - word\n"}, 
  {/* name */ "dummy_field", /* range */ "[23:17]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_efusectrl_reg__read_val_0[]  = {
  {/* name */ "sts_efuse_read_val_0", /* range */ "[31:0]", /* default */ "0x0", /* access */ "read-only", /* description */ "Efuse read value\n"}
};
field_const_t field_const_efusectrl_reg__prog_ctrl_0[]  = {
  {/* name */ "ctl_efuse_prog_req_0", /* range */ "[0:0]", /* default */ "0x0", /* access */ "read-write", /* description */ "Efuse program req\n"}, 
  {/* name */ "ctl_efuse_prog_bit_addr_0", /* range */ "[7:4]", /* default */ "0x0", /* access */ "read-write", /* description */ "Efuse program bit adress\n"}, 
  {/* name */ "ctl_efuse_prog_addr_0", /* range */ "[12:8]", /* default */ "0x0", /* access */ "read-write", /* description */ "Efuse program adress\n"}, 
  {/* name */ "ctl_efuse_prog_efuse_sel_0", /* range */ "[17:16]", /* default */ "0x0", /* access */ "read-write", /* description */ "Efuse selection\n"}, 
  {/* name */ "dummy_field", /* range */ "[23:18]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_efusectrl_reg__counter_ctrl_0_0[]  = {
  {/* name */ "ctl_efuse_cnt_init_0", /* range */ "[9:0]", /* default */ "0x10", /* access */ "read-write", /* description */ "Trpw value\n"}, 
  {/* name */ "ctl_efuse_cnt_trds_0", /* range */ "[19:10]", /* default */ "0x10", /* access */ "read-write", /* description */ "Trpi value\n"}, 
  {/* name */ "ctl_efuse_cnt_tfs_0", /* range */ "[29:20]", /* default */ "0x10", /* access */ "read-write", /* description */ "Tstp_csb value\n"}, 
  {/* name */ "dummy_field", /* range */ "[31:30]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_efusectrl_reg__counter_ctrl_0_1[]  = {
  {/* name */ "ctl_efuse_cnt_tpp_0", /* range */ "[9:0]", /* default */ "0x10", /* access */ "read-write", /* description */ "Trpw value\n"}, 
  {/* name */ "ctl_efuse_cnt_teh_0", /* range */ "[19:10]", /* default */ "0x10", /* access */ "read-write", /* description */ "Trpi value\n"}, 
  {/* name */ "ctl_efuse_cnt_tesr_0", /* range */ "[29:20]", /* default */ "0x10", /* access */ "read-write", /* description */ "Tstp_csb value\n"}, 
  {/* name */ "dummy_field", /* range */ "[31:30]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_efusectrl_reg__counter_ctrl_0_2[]  = {
  {/* name */ "ctl_efuse_cnt_trpw_0", /* range */ "[9:0]", /* default */ "0x10", /* access */ "read-write", /* description */ "Trpw value\n"}, 
  {/* name */ "ctl_efuse_cnt_trc_mod_0", /* range */ "[19:10]", /* default */ "0x10", /* access */ "read-write", /* description */ "Trpi value\n"}, 
  {/* name */ "dummy_field", /* range */ "[23:20]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_efusectrl_reg__misc_ctrl_1[]  = {
  {/* name */ "ctl_efuse_en_1", /* range */ "[0:0]", /* default */ "0x0", /* access */ "read-write", /* description */ "Enable efuse read/write\n"}, 
  {/* name */ "ctl_efuse_intr_clr_1", /* range */ "[1:1]", /* default */ "0x0", /* access */ "read-write", /* description */ "Enable efuse interrupt clear\n"}, 
  {/* name */ "ctl_efuse_prog_en_1", /* range */ "[4:4]", /* default */ "0x0", /* access */ "read-write", /* description */ "Enable programming\n"}, 
  {/* name */ "dummy_field", /* range */ "[7:5]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_efusectrl_reg__misc_sts_1[]  = {
  {/* name */ "sts_efuse_prog_blk_1", /* range */ "[0:0]", /* default */ "0x0", /* access */ "read-only", /* description */ "Efuse program blocked\n"}, 
  {/* name */ "sts_efuse_init_rd_byp_1", /* range */ "[20:20]", /* default */ "0x0", /* access */ "read-only", /* description */ "Efuse initial read bypassed\n"}, 
  {/* name */ "sts_efuse_curr_state_1", /* range */ "[27:24]", /* default */ "0x0", /* access */ "read-only", /* description */ "Efuse controller core current state\n"}, 
  {/* name */ "dummy_field", /* range */ "[31:28]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_efusectrl_reg__init_rd_value_1_0[]  = {
  {/* name */ "sts_efuse_init_rd_val_1_0", /* range */ "[31:0]", /* default */ "0x0", /* access */ "read-only", /* description */ "Efuse initial read value 0\n"}
};
field_const_t field_const_efusectrl_reg__init_rd_value_1_1[]  = {
  {/* name */ "sts_efuse_init_rd_val_1_1", /* range */ "[31:0]", /* default */ "0x0", /* access */ "read-only", /* description */ "Efuse initial read value 1\n"}
};
field_const_t field_const_efusectrl_reg__read_ctrl_1[]  = {
  {/* name */ "ctl_efuse_read_req_1", /* range */ "[0:0]", /* default */ "0x0", /* access */ "read-write", /* description */ "Efuse read req\n"}, 
  {/* name */ "ctl_efuse_read_addr_1", /* range */ "[8:4]", /* default */ "0x0", /* access */ "read-write", /* description */ "Efuse read adress\n"}, 
  {/* name */ "ctl_efuse_read_efuse_sel_1", /* range */ "[13:12]", /* default */ "0x0", /* access */ "read-write", /* description */ "Efuse selection\n"}, 
  {/* name */ "ctl_efuse_read_mode_1", /* range */ "[16:16]", /* default */ "0x0", /* access */ "read-write", /* description */ "Efuse read mode: 0 - half word, 1 - word\n"}, 
  {/* name */ "dummy_field", /* range */ "[23:17]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_efusectrl_reg__read_val_1[]  = {
  {/* name */ "sts_efuse_read_val_1", /* range */ "[31:0]", /* default */ "0x0", /* access */ "read-only", /* description */ "Efuse read value\n"}
};
field_const_t field_const_efusectrl_reg__prog_ctrl_1[]  = {
  {/* name */ "ctl_efuse_prog_req_1", /* range */ "[0:0]", /* default */ "0x0", /* access */ "read-write", /* description */ "Efuse program req\n"}, 
  {/* name */ "ctl_efuse_prog_bit_addr_1", /* range */ "[7:4]", /* default */ "0x0", /* access */ "read-write", /* description */ "Efuse program bit adress\n"}, 
  {/* name */ "ctl_efuse_prog_addr_1", /* range */ "[12:8]", /* default */ "0x0", /* access */ "read-write", /* description */ "Efuse program adress\n"}, 
  {/* name */ "ctl_efuse_prog_efuse_sel_1", /* range */ "[17:16]", /* default */ "0x0", /* access */ "read-write", /* description */ "Efuse selection\n"}, 
  {/* name */ "dummy_field", /* range */ "[23:18]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_efusectrl_reg__counter_ctrl_1_0[]  = {
  {/* name */ "ctl_efuse_cnt_init_1", /* range */ "[9:0]", /* default */ "0x10", /* access */ "read-write", /* description */ "Trpw value\n"}, 
  {/* name */ "ctl_efuse_cnt_trds_1", /* range */ "[19:10]", /* default */ "0x10", /* access */ "read-write", /* description */ "Trpi value\n"}, 
  {/* name */ "ctl_efuse_cnt_tfs_1", /* range */ "[29:20]", /* default */ "0x10", /* access */ "read-write", /* description */ "Tstp_csb value\n"}, 
  {/* name */ "dummy_field", /* range */ "[31:30]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_efusectrl_reg__counter_ctrl_1_1[]  = {
  {/* name */ "ctl_efuse_cnt_tpp_1", /* range */ "[9:0]", /* default */ "0x10", /* access */ "read-write", /* description */ "Trpw value\n"}, 
  {/* name */ "ctl_efuse_cnt_teh_1", /* range */ "[19:10]", /* default */ "0x10", /* access */ "read-write", /* description */ "Trpi value\n"}, 
  {/* name */ "ctl_efuse_cnt_tesr_1", /* range */ "[29:20]", /* default */ "0x10", /* access */ "read-write", /* description */ "Tstp_csb value\n"}, 
  {/* name */ "dummy_field", /* range */ "[31:30]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_efusectrl_reg__counter_ctrl_1_2[]  = {
  {/* name */ "ctl_efuse_cnt_trpw_1", /* range */ "[9:0]", /* default */ "0x10", /* access */ "read-write", /* description */ "Trpw value\n"}, 
  {/* name */ "ctl_efuse_cnt_trc_mod_1", /* range */ "[19:10]", /* default */ "0x10", /* access */ "read-write", /* description */ "Trpi value\n"}, 
  {/* name */ "dummy_field", /* range */ "[23:20]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_efusectrl_reg__inplay_init_rd_val[]  = {
  {/* name */ "sts_inplay_efuse_lock", /* range */ "[0:0]", /* default */ "0x0", /* access */ "read-only", /* description */ "If efuse is locked for future writes\n"}, 
  {/* name */ "sts_spiflash_present", /* range */ "[1:1]", /* default */ "0x0", /* access */ "read-only", /* description */ "If external spiflash present\n"}, 
  {/* name */ "sts_inplay_feature_sel", /* range */ "[7:4]", /* default */ "0x0", /* access */ "read-only", /* description */ "Inplay feature set selection\n"}, 
  {/* name */ "sts_inplay_security_key_sel", /* range */ "[11:8]", /* default */ "0x0", /* access */ "read-only", /* description */ "Inplay security key selection\n"}, 
  {/* name */ "sts_inplay_security_key_alg", /* range */ "[14:12]", /* default */ "0x0", /* access */ "read-only", /* description */ "Inplay security key algorithm selection\n"}, 
  {/* name */ "dummy_field", /* range */ "[15:15]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_efusectrl_reg__qspi_pin_mux_sel[]  = {
  {/* name */ "sts_qspi_0_pin_mux_sel", /* range */ "[2:0]", /* default */ "0x0", /* access */ "read-only", /* description */ "QSPI 0 pinmux selection\n"}, 
  {/* name */ "sts_qspi_2_pin_mux_sel", /* range */ "[6:4]", /* default */ "0x0", /* access */ "read-only", /* description */ "QSPI 2 pinmux selection\n"}, 
  {/* name */ "sts_qspi_3_pin_mux_sel", /* range */ "[10:8]", /* default */ "0x0", /* access */ "read-only", /* description */ "QSPI 3 pinmux selection\n"}, 
  {/* name */ "sts_qspi_4_pin_mux_sel", /* range */ "[14:12]", /* default */ "0x0", /* access */ "read-only", /* description */ "QSPI 4 pinmux selection\n"}, 
  {/* name */ "sts_qspi_5_pin_mux_sel", /* range */ "[18:16]", /* default */ "0x0", /* access */ "read-only", /* description */ "QSPI 5 pinmux selection\n"}, 
  {/* name */ "sts_qspi_3a_3b_sel", /* range */ "[24:24]", /* default */ "0x0", /* access */ "read-only", /* description */ "QSPI 3A/3B pad select: 0 - 3A, 1 -3B\n"}, 
  {/* name */ "sts_qspi_tvsl", /* range */ "[30:28]", /* default */ "0x0", /* access */ "read-only", /* description */ "Time to wait between power up and 1st CS low\n\n0 - 16 us\n\n1 - 32 us\n\n2 - 64 us\n\n3 - 128 us\n\n4 - 256 us\n\n5 - 512 us\n\n6 - 1024 us\n\n7 - 2048 us\n\n\n"}, 
  {/* name */ "dummy_field", /* range */ "[31:31]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_efusectrl_reg__uuid0[]  = {
  {/* name */ "sts_uuid_31_0", /* range */ "[31:0]", /* default */ "0x0", /* access */ "read-only", /* description */ "UUID [31:0]\n"}
};
field_const_t field_const_efusectrl_reg__uuid1[]  = {
  {/* name */ "sts_uuid_63_32", /* range */ "[31:0]", /* default */ "0x0", /* access */ "read-only", /* description */ "UUID [63:32]\n"}
};
field_const_t field_const_efusectrl_reg__uuid2[]  = {
  {/* name */ "sts_uuid_95_64", /* range */ "[31:0]", /* default */ "0x0", /* access */ "read-only", /* description */ "UUID [95:64]\n"}
};
field_const_t field_const_efusectrl_reg__uuid3[]  = {
  {/* name */ "sts_uuid_127_96", /* range */ "[31:0]", /* default */ "0x0", /* access */ "read-only", /* description */ "UUID [127:96]\n"}
};
field_const_t field_const_efusectrl_reg__customer_init_rd_value[]  = {
  {/* name */ "sts_customer_efuse_lock", /* range */ "[0:0]", /* default */ "0x0", /* access */ "read-only", /* description */ "Efuse block locked for future writes\n"}, 
  {/* name */ "sts_cm4_dbg_disable", /* range */ "[1:1]", /* default */ "0x0", /* access */ "read-only", /* description */ "Disable CM4 debugging port\n"}, 
  {/* name */ "sts_flash_encryption_enable", /* range */ "[2:2]", /* default */ "0x0", /* access */ "read-only", /* description */ "Enable flash data encryption\n"}, 
  {/* name */ "sts_flash_secure_boot_enable", /* range */ "[3:3]", /* default */ "0x0", /* access */ "read-only", /* description */ "Enable flash data encryption\n"}, 
  {/* name */ "sts_ram_secure_boot_enable", /* range */ "[4:4]", /* default */ "0x0", /* access */ "read-only", /* description */ "RAM secure boot enable\n"}, 
  {/* name */ "sts_ecc_len_secure_boot", /* range */ "[5:5]", /* default */ "0x0", /* access */ "read-only", /* description */ "0 - 192, 1 - 256\n"}, 
  {/* name */ "sts_default_if_en", /* range */ "[8:8]", /* default */ "0x0", /* access */ "read-only", /* description */ "Enable default interface\n"}, 
  {/* name */ "sts_default_if_sel", /* range */ "[14:12]", /* default */ "0x0", /* access */ "read-only", /* description */ "0 - uart 0\n\n1 - uart 1\n\n2 - spi slave\n\n3 - uart 0 backup location\n\n4 - uart 1 backup location\n\n"}, 
  {/* name */ "sts_rtc_not_installed", /* range */ "[16:16]", /* default */ "0x0", /* access */ "read-only", /* description */ "1 - RTC not installed\n"}, 
  {/* name */ "dummy_field", /* range */ "[23:17]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_efusectrl_reg__customer_id[]  = {
  {/* name */ "sts_customer_id", /* range */ "[31:0]", /* default */ "0x0", /* access */ "read-only", /* description */ "Customer defined product, manufactore ID, etc.\n"}
};

field_const_array_t reg_pnt_list__efusectrl_reg[NUM_REGS__EFUSECTRL_REG] = {
  { /* pfield */ field_const_efusectrl_reg__intr_status, /* size */ 7}, 
  { /* pfield */ field_const_efusectrl_reg__intr_mask_status, /* size */ 7}, 
  { /* pfield */ field_const_efusectrl_reg__intr_clr, /* size */ 7}, 
  { /* pfield */ field_const_efusectrl_reg__intr_set, /* size */ 7}, 
  { /* pfield */ field_const_efusectrl_reg__intr_mask_set, /* size */ 7}, 
  { /* pfield */ field_const_efusectrl_reg__intr_mask_clr, /* size */ 7}, 
  { /* pfield */ field_const_efusectrl_reg__misc_ctrl_0, /* size */ 4}, 
  { /* pfield */ field_const_efusectrl_reg__misc_sts_0, /* size */ 4}, 
  { /* pfield */ field_const_efusectrl_reg__init_rd_value_0_0, /* size */ 1}, 
  { /* pfield */ field_const_efusectrl_reg__init_rd_value_0_1, /* size */ 1}, 
  { /* pfield */ field_const_efusectrl_reg__read_ctrl_0, /* size */ 5}, 
  { /* pfield */ field_const_efusectrl_reg__read_val_0, /* size */ 1}, 
  { /* pfield */ field_const_efusectrl_reg__prog_ctrl_0, /* size */ 5}, 
  { /* pfield */ field_const_efusectrl_reg__counter_ctrl_0_0, /* size */ 4}, 
  { /* pfield */ field_const_efusectrl_reg__counter_ctrl_0_1, /* size */ 4}, 
  { /* pfield */ field_const_efusectrl_reg__counter_ctrl_0_2, /* size */ 3}, 
  { /* pfield */ field_const_efusectrl_reg__misc_ctrl_1, /* size */ 4}, 
  { /* pfield */ field_const_efusectrl_reg__misc_sts_1, /* size */ 4}, 
  { /* pfield */ field_const_efusectrl_reg__init_rd_value_1_0, /* size */ 1}, 
  { /* pfield */ field_const_efusectrl_reg__init_rd_value_1_1, /* size */ 1}, 
  { /* pfield */ field_const_efusectrl_reg__read_ctrl_1, /* size */ 5}, 
  { /* pfield */ field_const_efusectrl_reg__read_val_1, /* size */ 1}, 
  { /* pfield */ field_const_efusectrl_reg__prog_ctrl_1, /* size */ 5}, 
  { /* pfield */ field_const_efusectrl_reg__counter_ctrl_1_0, /* size */ 4}, 
  { /* pfield */ field_const_efusectrl_reg__counter_ctrl_1_1, /* size */ 4}, 
  { /* pfield */ field_const_efusectrl_reg__counter_ctrl_1_2, /* size */ 3}, 
  { /* pfield */ field_const_efusectrl_reg__inplay_init_rd_val, /* size */ 6}, 
  { /* pfield */ field_const_efusectrl_reg__qspi_pin_mux_sel, /* size */ 8}, 
  { /* pfield */ field_const_efusectrl_reg__uuid0, /* size */ 1}, 
  { /* pfield */ field_const_efusectrl_reg__uuid1, /* size */ 1}, 
  { /* pfield */ field_const_efusectrl_reg__uuid2, /* size */ 1}, 
  { /* pfield */ field_const_efusectrl_reg__uuid3, /* size */ 1}, 
  { /* pfield */ field_const_efusectrl_reg__customer_init_rd_value, /* size */ 10}, 
  { /* pfield */ field_const_efusectrl_reg__customer_id, /* size */ 1}
};
