/////////////////////////////////////////////////////////////////////////////////
// This file has been automatically generated by register_slave.pl version dc9b7d3
/////////////////////////////////////////////////////////////////////////////////

// type declaration
#ifndef __REG_CONST_T
#define __REG_CONST_T

#ifndef REG_CONST_NAME_STRING_MAX_LEN   
#define REG_CONST_NAME_STRING_MAX_LEN 64
#endif // REG_CONST_NAME_STRING_MAX_LEN
#ifndef REG_CONST_DESC_STRING_MAX_LEN
#define REG_CONST_DESC_STRING_MAX_LEN 512
#endif // REG_CONST_DESC_STRING_MAX_LEN
typedef struct {
	char name[REG_CONST_NAME_STRING_MAX_LEN];
	DWORD address;
	DWORD def;
	char desc[REG_CONST_DESC_STRING_MAX_LEN];
} reg_const_t;
typedef struct {
	char name[REG_CONST_NAME_STRING_MAX_LEN];
	char range[32];
	char def[32];
	char access[32];
	char desc[REG_CONST_DESC_STRING_MAX_LEN];
} field_const_t;
typedef struct {
	field_const_t *pfield;
	DWORD size;
} field_const_array_t;
#endif // __REG_CONST_T

#define NUM_REGS__RFTRX_REG  43
/* { reg_const_rftrx_reg, 43, "rftrx_reg"},  */ 
static reg_const_t reg_const_rftrx_reg[NUM_REGS__RFTRX_REG] = {
  {/* name */ "cpll_reg_1to4", /* address */ 0x46a03080, /* default */ 0x0cd94490, /* description */ "CPLL register 1:4\n"}, 
  {/* name */ "cpll_reg_5to6", /* address */ 0x46a03084, /* default */ 0x00004c00, /* description */ "CPLL register 5:6\n"}, 
  {/* name */ "cpll_reg_1to3_1m", /* address */ 0x46a03088, /* default */ 0x005944d0, /* description */ "CPLL register 1:4\n"}, 
  {/* name */ "mpll_2p4_reg_5to8", /* address */ 0x46a03090, /* default */ 0x3b841710, /* description */ "MPLL 2.4G register 5:8\n"}, 
  {/* name */ "mpll_2p4_reg_9to12", /* address */ 0x46a03094, /* default */ 0x800d814a, /* description */ "MPLL 2.4G register 9:12\n"}, 
  {/* name */ "mpll_2p4_reg_13to14", /* address */ 0x46a03098, /* default */ 0x00004a22, /* description */ "MPLL 2.4G register 13:14\n"}, 
  {/* name */ "mpll_5p8_reg_5to8", /* address */ 0x46a030a0, /* default */ 0x3b84170c, /* description */ "MPLL 5.8G register 5:8\n"}, 
  {/* name */ "mpll_5p8_reg_9to12", /* address */ 0x46a030a4, /* default */ 0x80128144, /* description */ "MPLL 5.8G register 9:12\n"}, 
  {/* name */ "mpll_5p8_reg_13to14", /* address */ 0x46a030a8, /* default */ 0x00004888, /* description */ "MPLL 5.8G register 13:14\n"}, 
  {/* name */ "mpll_reg_9_2m", /* address */ 0x46a030ac, /* default */ 0x000044ce, /* description */ "MPLL register 9 for 2M PHY (2.4G and 5.8G)\n"}, 
  {/* name */ "rx_2p4_reg_1to4", /* address */ 0x46a030b4, /* default */ 0x700cff5c, /* description */ "RX 2.4G register 1:4\n"}, 
  {/* name */ "rx_2p4_reg_5to8", /* address */ 0x46a030b8, /* default */ 0x00006000, /* description */ "RX 2.4G register 5:8\n"}, 
  {/* name */ "rx_5p8_reg_1to4", /* address */ 0x46a030bc, /* default */ 0x0100ff5c, /* description */ "RX 5.8G register 1:4\n"}, 
  {/* name */ "rx_5p8_reg_5to8", /* address */ 0x46a030c0, /* default */ 0x00000000, /* description */ "RX 5.8G register 5:8\n"}, 
  {/* name */ "rx_reg_3_2m", /* address */ 0x46a030c4, /* default */ 0x00000000, /* description */ "RX register 3 for 2M PHY (2.4G and 5.8G)\n"}, 
  {/* name */ "tx_reg", /* address */ 0x46a030d0, /* default */ 0x007f007f, /* description */ "TX registers\n"}, 
  {/* name */ "sdadc_reg_1to4_1m", /* address */ 0x46a030e0, /* default */ 0x005588a2, /* description */ "SDADC register 1:4 for 1M PHY\n"}, 
  {/* name */ "sdadc_reg_1to4_2m", /* address */ 0x46a030e4, /* default */ 0x00cceea2, /* description */ "SDADC register 1:4 for 2M PHY\n"}, 
  {/* name */ "sdadc_reg_5to8_1m", /* address */ 0x46a030e8, /* default */ 0x759cf0f0, /* description */ "SDADC register 5:8 for 1M PHY\n"}, 
  {/* name */ "sdadc_reg_5to8_2m", /* address */ 0x46a030ec, /* default */ 0x16387070, /* description */ "SDADC register 5:8 for 2M PHY\n"}, 
  {/* name */ "sdadc_reg_9to12_1m", /* address */ 0x46a030f0, /* default */ 0x76848484, /* description */ "SDADC register 9:12 for 1M PHY\n"}, 
  {/* name */ "sdadc_reg_9to12_2m", /* address */ 0x46a030f4, /* default */ 0x32848484, /* description */ "SDADC register 9:12 for 2M PHY\n"}, 
  {/* name */ "agc_reg", /* address */ 0x46a03100, /* default */ 0x008a1002, /* description */ "AGC registers\n"}, 
  {/* name */ "rftrx_test_mux_ctrl", /* address */ 0x46a03110, /* default */ 0x00000000, /* description */ "RF TRX test mux control\n"}, 
  {/* name */ "cpll_status", /* address */ 0x46a03120, /* default */ 0x00000000, /* description */ "CPLL status\n"}, 
  {/* name */ "mpll_2p4_status", /* address */ 0x46a03128, /* default */ 0x00000000, /* description */ "2.4G MPLL status\n"}, 
  {/* name */ "mpll_5p8_status", /* address */ 0x46a03130, /* default */ 0x00000000, /* description */ "5.8G MPLL status\n"}, 
  {/* name */ "xo_status", /* address */ 0x46a03138, /* default */ 0x00000000, /* description */ "XO status\n"}, 
  {/* name */ "rftrx_misc_ctrl", /* address */ 0x46a0313c, /* default */ 0x00000010, /* description */ "RF TRX miscellaneous control\n"}, 
  {/* name */ "mpll_2p4_reg_1to4", /* address */ 0x46a03140, /* default */ 0x04b10000, /* description */ "MPLL 2.4G register 1 .. 4. These registers will be used as default value to overwrite trigger memory values\n"}, 
  {/* name */ "mpll_5p8_reg_1to4", /* address */ 0x46a03144, /* default */ 0x00000000, /* description */ "MPLL 5.8G register 1 .. 4. These registers will be used as default value to overwrite trigger memory values\n"}, 
  {/* name */ "trx_spare", /* address */ 0x46a03150, /* default */ 0x00000000, /* description */ "spare status register from RF analog\n"}, 
  {/* name */ "pll_trig_misc_ctrl", /* address */ 0x46a03180, /* default */ 0x00000001, /* description */ "Misc control\n"}, 
  {/* name */ "pll_trig_misc_status", /* address */ 0x46a03188, /* default */ 0x00000000, /* description */ "Misc status\n"}, 
  {/* name */ "rx_2p4_pll_trig_ctrl", /* address */ 0x46a031c0, /* default */ 0x00010001, /* description */ "Trigger control for RX 2.4G rate\n"}, 
  {/* name */ "rx_5p8_pll_trig_ctrl", /* address */ 0x46a031c8, /* default */ 0x00010001, /* description */ "Trigger control for RX 5.8G rate\n"}, 
  {/* name */ "tx_2p4_pll_trig_ctrl", /* address */ 0x46a031d0, /* default */ 0x00010801, /* description */ "Trigger control for TX 2.4G rate\n"}, 
  {/* name */ "tx_5p8_pll_trig_ctrl", /* address */ 0x46a031d8, /* default */ 0x00010001, /* description */ "Trigger control for TX 5.8G rate\n"}, 
  {/* name */ "software_pll_trig_ctrl", /* address */ 0x46a031e0, /* default */ 0x00000000, /* description */ "Software trigger control\n"}, 
  {/* name */ "tx_scale_hp_lp", /* address */ 0x46a031e8, /* default */ 0x00809a80, /* description */ ""}, 
  {/* name */ "trx_pll_trig_mux_ctrl", /* address */ 0x46a031ec, /* default */ 0x00001111, /* description */ "MUX control for trx_trig\n"}, 
  {/* name */ "en_cpll_non_2m_rx", /* address */ 0x46a031f8, /* default */ 0x00000000, /* description */ "Manually enable CPLL when RX rate is not 2Mbps\n"}, 
  {/* name */ "pmu_trx_id", /* address */ 0x46a03200, /* default */ 0x00000000, /* description */ "ID of analog blocks (PMU and TRX)\n"}
};

field_const_t field_const_rftrx_reg__cpll_reg_1to4[]  = {
  {/* name */ "reg1", /* range */ "[7:0]", /* default */ "0x90", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg2", /* range */ "[15:8]", /* default */ "0x44", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg3", /* range */ "[23:16]", /* default */ "0xd9", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg4", /* range */ "[31:24]", /* default */ "0x0c", /* access */ "read-write", /* description */ ""}
};
field_const_t field_const_rftrx_reg__cpll_reg_5to6[]  = {
  {/* name */ "reg5", /* range */ "[7:0]", /* default */ "0x00", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg6", /* range */ "[15:8]", /* default */ "0x4c", /* access */ "read-write", /* description */ ""}
};
field_const_t field_const_rftrx_reg__cpll_reg_1to3_1m[]  = {
  {/* name */ "reg1", /* range */ "[7:0]", /* default */ "0xd0", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg2", /* range */ "[15:8]", /* default */ "0x44", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg3", /* range */ "[23:16]", /* default */ "0x59", /* access */ "read-write", /* description */ ""}
};
field_const_t field_const_rftrx_reg__mpll_2p4_reg_5to8[]  = {
  {/* name */ "reg5", /* range */ "[7:0]", /* default */ "0x10", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg6", /* range */ "[15:8]", /* default */ "0x17", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg7", /* range */ "[23:16]", /* default */ "0x84", /* access */ "read-write", /* description */ "this register value will be used to overwrite trigger memory values\n"}, 
  {/* name */ "reg8", /* range */ "[31:24]", /* default */ "0x3b", /* access */ "read-write", /* description */ ""}
};
field_const_t field_const_rftrx_reg__mpll_2p4_reg_9to12[]  = {
  {/* name */ "reg9", /* range */ "[7:0]", /* default */ "0x4a", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg10", /* range */ "[15:8]", /* default */ "0x81", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg11", /* range */ "[23:16]", /* default */ "0x0d", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg12", /* range */ "[31:24]", /* default */ "0x80", /* access */ "read-write", /* description */ ""}
};
field_const_t field_const_rftrx_reg__mpll_2p4_reg_13to14[]  = {
  {/* name */ "reg13", /* range */ "[7:0]", /* default */ "0x22", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg14", /* range */ "[15:8]", /* default */ "0x4a", /* access */ "read-write", /* description */ ""}
};
field_const_t field_const_rftrx_reg__mpll_5p8_reg_5to8[]  = {
  {/* name */ "reg5", /* range */ "[7:0]", /* default */ "0x0c", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg6", /* range */ "[15:8]", /* default */ "0x17", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg7", /* range */ "[23:16]", /* default */ "0x84", /* access */ "read-write", /* description */ "this register value will be used to overwrite trigger memory values\n"}, 
  {/* name */ "reg8", /* range */ "[31:24]", /* default */ "0x3b", /* access */ "read-write", /* description */ ""}
};
field_const_t field_const_rftrx_reg__mpll_5p8_reg_9to12[]  = {
  {/* name */ "reg9", /* range */ "[7:0]", /* default */ "0x44", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg10", /* range */ "[15:8]", /* default */ "0x81", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg11", /* range */ "[23:16]", /* default */ "0x12", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg12", /* range */ "[31:24]", /* default */ "0x80", /* access */ "read-write", /* description */ ""}
};
field_const_t field_const_rftrx_reg__mpll_5p8_reg_13to14[]  = {
  {/* name */ "reg13", /* range */ "[7:0]", /* default */ "0x88", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg14", /* range */ "[15:8]", /* default */ "0x48", /* access */ "read-write", /* description */ ""}
};
field_const_t field_const_rftrx_reg__mpll_reg_9_2m[]  = {
  {/* name */ "2p4_reg9", /* range */ "[7:0]", /* default */ "0xce", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "5p8_reg9", /* range */ "[15:8]", /* default */ "0x44", /* access */ "read-write", /* description */ ""}
};
field_const_t field_const_rftrx_reg__rx_2p4_reg_1to4[]  = {
  {/* name */ "reg1", /* range */ "[7:0]", /* default */ "0x5c", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg2", /* range */ "[15:8]", /* default */ "0xff", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg3", /* range */ "[23:16]", /* default */ "0x0C", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg4", /* range */ "[31:24]", /* default */ "0x70", /* access */ "read-write", /* description */ ""}
};
field_const_t field_const_rftrx_reg__rx_2p4_reg_5to8[]  = {
  {/* name */ "reg5", /* range */ "[7:0]", /* default */ "0x0", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg6", /* range */ "[15:8]", /* default */ "0x60", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg7", /* range */ "[23:16]", /* default */ "0x0", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg8", /* range */ "[31:24]", /* default */ "0x0", /* access */ "read-write", /* description */ ""}
};
field_const_t field_const_rftrx_reg__rx_5p8_reg_1to4[]  = {
  {/* name */ "reg1", /* range */ "[7:0]", /* default */ "0x5c", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg2", /* range */ "[15:8]", /* default */ "0xff", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg3", /* range */ "[23:16]", /* default */ "0x00", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg4", /* range */ "[31:24]", /* default */ "0x01", /* access */ "read-write", /* description */ ""}
};
field_const_t field_const_rftrx_reg__rx_5p8_reg_5to8[]  = {
  {/* name */ "reg5", /* range */ "[7:0]", /* default */ "0x0", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg6", /* range */ "[15:8]", /* default */ "0x0", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg7", /* range */ "[23:16]", /* default */ "0x0", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg8", /* range */ "[31:24]", /* default */ "0x0", /* access */ "read-write", /* description */ ""}
};
field_const_t field_const_rftrx_reg__rx_reg_3_2m[]  = {
  {/* name */ "2p4_reg3", /* range */ "[7:0]", /* default */ "0x0", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "5p8_reg3", /* range */ "[15:8]", /* default */ "0x0", /* access */ "read-write", /* description */ ""}
};
field_const_t field_const_rftrx_reg__tx_reg[]  = {
  {/* name */ "tx_2p4_reg1", /* range */ "[7:0]", /* default */ "0x7f", /* access */ "read-write", /* description */ "this register value will be used to overwrite trigger memory values\n"}, 
  {/* name */ "tx_2p4_reg2", /* range */ "[15:8]", /* default */ "0x00", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "tx_5p8_reg1", /* range */ "[23:16]", /* default */ "0x7f", /* access */ "read-write", /* description */ "this register value will be used to overwrite trigger memory values\n"}, 
  {/* name */ "tx_5p8_reg2", /* range */ "[31:24]", /* default */ "0x00", /* access */ "read-write", /* description */ ""}
};
field_const_t field_const_rftrx_reg__sdadc_reg_1to4_1m[]  = {
  {/* name */ "reg1", /* range */ "[7:0]", /* default */ "0xa2", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg2", /* range */ "[15:8]", /* default */ "0x88", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg3", /* range */ "[23:16]", /* default */ "0x55", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg4", /* range */ "[31:24]", /* default */ "0x00", /* access */ "read-write", /* description */ ""}
};
field_const_t field_const_rftrx_reg__sdadc_reg_1to4_2m[]  = {
  {/* name */ "reg1", /* range */ "[7:0]", /* default */ "0xa2", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg2", /* range */ "[15:8]", /* default */ "0xEE", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg3", /* range */ "[23:16]", /* default */ "0xCC", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg4", /* range */ "[31:24]", /* default */ "0x00", /* access */ "read-write", /* description */ ""}
};
field_const_t field_const_rftrx_reg__sdadc_reg_5to8_1m[]  = {
  {/* name */ "reg5", /* range */ "[7:0]", /* default */ "0xf0", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg6", /* range */ "[15:8]", /* default */ "0xf0", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg7", /* range */ "[23:16]", /* default */ "0x9c", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg8", /* range */ "[31:24]", /* default */ "0x75", /* access */ "read-write", /* description */ ""}
};
field_const_t field_const_rftrx_reg__sdadc_reg_5to8_2m[]  = {
  {/* name */ "reg5", /* range */ "[7:0]", /* default */ "0x70", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg6", /* range */ "[15:8]", /* default */ "0x70", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg7", /* range */ "[23:16]", /* default */ "0x38", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg8", /* range */ "[31:24]", /* default */ "0x16", /* access */ "read-write", /* description */ ""}
};
field_const_t field_const_rftrx_reg__sdadc_reg_9to12_1m[]  = {
  {/* name */ "reg9", /* range */ "[7:0]", /* default */ "0x84", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg10", /* range */ "[15:8]", /* default */ "0x84", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg11", /* range */ "[23:16]", /* default */ "0x84", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg12", /* range */ "[31:24]", /* default */ "0x76", /* access */ "read-write", /* description */ ""}
};
field_const_t field_const_rftrx_reg__sdadc_reg_9to12_2m[]  = {
  {/* name */ "reg9", /* range */ "[7:0]", /* default */ "0x84", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg10", /* range */ "[15:8]", /* default */ "0x84", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg11", /* range */ "[23:16]", /* default */ "0x84", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg12", /* range */ "[31:24]", /* default */ "0x32", /* access */ "read-write", /* description */ ""}
};
field_const_t field_const_rftrx_reg__agc_reg[]  = {
  {/* name */ "reg1", /* range */ "[7:0]", /* default */ "0x02", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg2", /* range */ "[15:8]", /* default */ "0x10", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg3", /* range */ "[23:16]", /* default */ "0x8A", /* access */ "read-write", /* description */ ""}
};
field_const_t field_const_rftrx_reg__rftrx_test_mux_ctrl[]  = {
  {/* name */ "block", /* range */ "[3:0]", /* default */ "0x0", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "subblock", /* range */ "[6:4]", /* default */ "0x0", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "node", /* range */ "[10:8]", /* default */ "0x0", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "dummy_field", /* range */ "[15:11]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_rftrx_reg__cpll_status[]  = {
  {/* name */ "sts_cpll_locked", /* range */ "[0:0]", /* default */ "0x0", /* access */ "read-only", /* description */ ""}, 
  {/* name */ "dummy_field", /* range */ "[7:1]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_rftrx_reg__mpll_2p4_status[]  = {
  {/* name */ "sts_mpll_2p4_cal_result", /* range */ "[19:0]", /* default */ "0x0", /* access */ "read-only", /* description */ ""}, 
  {/* name */ "sts_mpll_2p4_crse_result", /* range */ "[28:20]", /* default */ "0x0", /* access */ "read-only", /* description */ ""}, 
  {/* name */ "sts_mpll_2p4_locked", /* range */ "[31:31]", /* default */ "0x0", /* access */ "read-only", /* description */ ""}
};
field_const_t field_const_rftrx_reg__mpll_5p8_status[]  = {
  {/* name */ "sts_mpll_5p8_cal_result", /* range */ "[19:0]", /* default */ "0x0", /* access */ "read-only", /* description */ ""}, 
  {/* name */ "sts_mpll_5p8_crse_result", /* range */ "[28:20]", /* default */ "0x0", /* access */ "read-only", /* description */ ""}, 
  {/* name */ "sts_mpll_5p8_locked", /* range */ "[31:31]", /* default */ "0x0", /* access */ "read-only", /* description */ ""}
};
field_const_t field_const_rftrx_reg__xo_status[]  = {
  {/* name */ "sts_xo_gt_target", /* range */ "[0:0]", /* default */ "0x0", /* access */ "read-only", /* description */ ""}, 
  {/* name */ "sts_xo_status", /* range */ "[9:4]", /* default */ "0x0", /* access */ "read-only", /* description */ ""}, 
  {/* name */ "dummy_field", /* range */ "[15:10]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_rftrx_reg__rftrx_misc_ctrl[]  = {
  {/* name */ "rx_cm_measure_en", /* range */ "[0:0]", /* default */ "0x0", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "ctl_clk_xo_x2_to_digi_en", /* range */ "[4:4]", /* default */ "0x1", /* access */ "read-write", /* description */ "Enable XO double clock to digital\n"}, 
  {/* name */ "ctl_clk_cpll_to_digi_en", /* range */ "[8:8]", /* default */ "0x0", /* access */ "read-write", /* description */ "Enable CPLL clock to digital\n"}, 
  {/* name */ "ctl_clk_cpll_to_sadc_en_force", /* range */ "[12:12]", /* default */ "0x0", /* access */ "read-write", /* description */ "Force enable CPLL to sigma-deta adc clock. If not force based on rate.\n"}, 
  {/* name */ "dummy_field", /* range */ "[15:13]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_rftrx_reg__mpll_2p4_reg_1to4[]  = {
  {/* name */ "reg1", /* range */ "[7:0]", /* default */ "0x0", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg2", /* range */ "[15:8]", /* default */ "0x0", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg3", /* range */ "[23:16]", /* default */ "0xb1", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg4", /* range */ "[27:24]", /* default */ "0x4", /* access */ "read-write", /* description */ "only contain 4 LSB of reg 4. Assuming 4 MSB's are always 0\n"}, 
  {/* name */ "dummy_field", /* range */ "[31:28]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_rftrx_reg__mpll_5p8_reg_1to4[]  = {
  {/* name */ "reg1", /* range */ "[7:0]", /* default */ "0x0", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg2", /* range */ "[15:8]", /* default */ "0x0", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg3", /* range */ "[23:16]", /* default */ "0x0", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "reg4", /* range */ "[27:24]", /* default */ "0x0", /* access */ "read-write", /* description */ "only contain 4 LSB of reg 4. Assuming 4 MSB's are always 0\n"}, 
  {/* name */ "dummy_field", /* range */ "[31:28]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_rftrx_reg__trx_spare[]  = {
  {/* name */ "sts_trx_spare", /* range */ "[1:0]", /* default */ "0x0", /* access */ "read-only", /* description */ "Spare status register\n"}, 
  {/* name */ "dummy_field", /* range */ "[7:2]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_rftrx_reg__pll_trig_misc_ctrl[]  = {
  {/* name */ "ctl_pll_trig_enable", /* range */ "[0:0]", /* default */ "0x1", /* access */ "read-write", /* description */ "enable signal for the whole block\n"}, 
  {/* name */ "ctl_pll_trig_apb_access_enable", /* range */ "[4:4]", /* default */ "0x0", /* access */ "read-write", /* description */ "Allow APB access to the memory\n"}, 
  {/* name */ "dummy_field", /* range */ "[7:5]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_rftrx_reg__pll_trig_misc_status[]  = {
  {/* name */ "sts_pll_trig_curr_state", /* range */ "[1:0]", /* default */ "0x0", /* access */ "read-only", /* description */ "Current FSM state\n"}, 
  {/* name */ "dummy_field", /* range */ "[7:2]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_rftrx_reg__rx_2p4_pll_trig_ctrl[]  = {
  {/* name */ "enable", /* range */ "[0:0]", /* default */ "0x1", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "base_addr", /* range */ "[13:4]", /* default */ "0x0", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "right_shift", /* range */ "[16:16]", /* default */ "0x1", /* access */ "read-write", /* description */ "Right shift channel idx by 1 (in case only need to support 40 channels)\n"}, 
  {/* name */ "dummy_field", /* range */ "[23:17]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_rftrx_reg__rx_5p8_pll_trig_ctrl[]  = {
  {/* name */ "enable", /* range */ "[0:0]", /* default */ "0x1", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "base_addr", /* range */ "[13:4]", /* default */ "0x0", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "right_shift", /* range */ "[16:16]", /* default */ "0x1", /* access */ "read-write", /* description */ "Right shift channel idx by 1 (in case only need to support 40 channels)\n"}, 
  {/* name */ "dummy_field", /* range */ "[23:17]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_rftrx_reg__tx_2p4_pll_trig_ctrl[]  = {
  {/* name */ "enable", /* range */ "[0:0]", /* default */ "0x1", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "base_addr", /* range */ "[13:4]", /* default */ "0x80", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "right_shift", /* range */ "[16:16]", /* default */ "0x1", /* access */ "read-write", /* description */ "Right shift channel idx by 1 (in case only need to support 40 channels)\n"}, 
  {/* name */ "dummy_field", /* range */ "[23:17]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_rftrx_reg__tx_5p8_pll_trig_ctrl[]  = {
  {/* name */ "enable", /* range */ "[0:0]", /* default */ "0x1", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "base_addr", /* range */ "[13:4]", /* default */ "0x0", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "right_shift", /* range */ "[16:16]", /* default */ "0x1", /* access */ "read-write", /* description */ "Right shift channel idx by 1 (in case only need to support 40 channels)\n"}, 
  {/* name */ "dummy_field", /* range */ "[23:17]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_rftrx_reg__software_pll_trig_ctrl[]  = {
  {/* name */ "enable", /* range */ "[0:0]", /* default */ "0x0", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "base_addr", /* range */ "[13:4]", /* default */ "0x0", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "trigger", /* range */ "[16:16]", /* default */ "0x0", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "rate", /* range */ "[20:20]", /* default */ "0x0", /* access */ "read-write", /* description */ "0 - 1M, 1 - 2M\n"}, 
  {/* name */ "freq_band", /* range */ "[21:21]", /* default */ "0x0", /* access */ "read-write", /* description */ "0 - 2.4G, 1 - 5.8G\n"}, 
  {/* name */ "tx_rx", /* range */ "[22:22]", /* default */ "0x0", /* access */ "read-write", /* description */ "0 - rx, 1 - tx\n"}, 
  {/* name */ "dummy_field", /* range */ "[23:23]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_rftrx_reg__tx_scale_hp_lp[]  = {
  {/* name */ "ctl_tx_scale_lp_1m", /* range */ "[7:0]", /* default */ "0x80", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "ctl_tx_scale_hp", /* range */ "[15:8]", /* default */ "0x9a", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "ctl_tx_scale_lp_2m", /* range */ "[23:16]", /* default */ "0x80", /* access */ "read-write", /* description */ ""}
};
field_const_t field_const_rftrx_reg__trx_pll_trig_mux_ctrl[]  = {
  {/* name */ "ctl_trig_to_ctrl_mpll_freq", /* range */ "[0:0]", /* default */ "0x1", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "ctl_trig_to_ctrl_mpll_vco_buf_ldo", /* range */ "[4:4]", /* default */ "0x1", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "ctl_trig_to_ctrl_tx_hp_scale_factor", /* range */ "[8:8]", /* default */ "0x1", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "ctl_trig_to_ctrl_pa_gain", /* range */ "[12:12]", /* default */ "0x1", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "dummy_field", /* range */ "[15:13]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_rftrx_reg__en_cpll_non_2m_rx[]  = {
  {/* name */ "ctl_en_cpll_non_2m_rx", /* range */ "[0:0]", /* default */ "0x0", /* access */ "read-write", /* description */ ""}, 
  {/* name */ "dummy_field", /* range */ "[7:1]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_rftrx_reg__pmu_trx_id[]  = {
  {/* name */ "sts_pmu_id", /* range */ "[3:0]", /* default */ "0x0", /* access */ "read-only", /* description */ ""}, 
  {/* name */ "sts_trx_id", /* range */ "[7:4]", /* default */ "0x0", /* access */ "read-only", /* description */ ""}
};

field_const_array_t reg_pnt_list__rftrx_reg[NUM_REGS__RFTRX_REG] = {
  { /* pfield */ field_const_rftrx_reg__cpll_reg_1to4, /* size */ 4}, 
  { /* pfield */ field_const_rftrx_reg__cpll_reg_5to6, /* size */ 2}, 
  { /* pfield */ field_const_rftrx_reg__cpll_reg_1to3_1m, /* size */ 3}, 
  { /* pfield */ field_const_rftrx_reg__mpll_2p4_reg_5to8, /* size */ 4}, 
  { /* pfield */ field_const_rftrx_reg__mpll_2p4_reg_9to12, /* size */ 4}, 
  { /* pfield */ field_const_rftrx_reg__mpll_2p4_reg_13to14, /* size */ 2}, 
  { /* pfield */ field_const_rftrx_reg__mpll_5p8_reg_5to8, /* size */ 4}, 
  { /* pfield */ field_const_rftrx_reg__mpll_5p8_reg_9to12, /* size */ 4}, 
  { /* pfield */ field_const_rftrx_reg__mpll_5p8_reg_13to14, /* size */ 2}, 
  { /* pfield */ field_const_rftrx_reg__mpll_reg_9_2m, /* size */ 2}, 
  { /* pfield */ field_const_rftrx_reg__rx_2p4_reg_1to4, /* size */ 4}, 
  { /* pfield */ field_const_rftrx_reg__rx_2p4_reg_5to8, /* size */ 4}, 
  { /* pfield */ field_const_rftrx_reg__rx_5p8_reg_1to4, /* size */ 4}, 
  { /* pfield */ field_const_rftrx_reg__rx_5p8_reg_5to8, /* size */ 4}, 
  { /* pfield */ field_const_rftrx_reg__rx_reg_3_2m, /* size */ 2}, 
  { /* pfield */ field_const_rftrx_reg__tx_reg, /* size */ 4}, 
  { /* pfield */ field_const_rftrx_reg__sdadc_reg_1to4_1m, /* size */ 4}, 
  { /* pfield */ field_const_rftrx_reg__sdadc_reg_1to4_2m, /* size */ 4}, 
  { /* pfield */ field_const_rftrx_reg__sdadc_reg_5to8_1m, /* size */ 4}, 
  { /* pfield */ field_const_rftrx_reg__sdadc_reg_5to8_2m, /* size */ 4}, 
  { /* pfield */ field_const_rftrx_reg__sdadc_reg_9to12_1m, /* size */ 4}, 
  { /* pfield */ field_const_rftrx_reg__sdadc_reg_9to12_2m, /* size */ 4}, 
  { /* pfield */ field_const_rftrx_reg__agc_reg, /* size */ 3}, 
  { /* pfield */ field_const_rftrx_reg__rftrx_test_mux_ctrl, /* size */ 4}, 
  { /* pfield */ field_const_rftrx_reg__cpll_status, /* size */ 2}, 
  { /* pfield */ field_const_rftrx_reg__mpll_2p4_status, /* size */ 3}, 
  { /* pfield */ field_const_rftrx_reg__mpll_5p8_status, /* size */ 3}, 
  { /* pfield */ field_const_rftrx_reg__xo_status, /* size */ 3}, 
  { /* pfield */ field_const_rftrx_reg__rftrx_misc_ctrl, /* size */ 5}, 
  { /* pfield */ field_const_rftrx_reg__mpll_2p4_reg_1to4, /* size */ 5}, 
  { /* pfield */ field_const_rftrx_reg__mpll_5p8_reg_1to4, /* size */ 5}, 
  { /* pfield */ field_const_rftrx_reg__trx_spare, /* size */ 2}, 
  { /* pfield */ field_const_rftrx_reg__pll_trig_misc_ctrl, /* size */ 3}, 
  { /* pfield */ field_const_rftrx_reg__pll_trig_misc_status, /* size */ 2}, 
  { /* pfield */ field_const_rftrx_reg__rx_2p4_pll_trig_ctrl, /* size */ 4}, 
  { /* pfield */ field_const_rftrx_reg__rx_5p8_pll_trig_ctrl, /* size */ 4}, 
  { /* pfield */ field_const_rftrx_reg__tx_2p4_pll_trig_ctrl, /* size */ 4}, 
  { /* pfield */ field_const_rftrx_reg__tx_5p8_pll_trig_ctrl, /* size */ 4}, 
  { /* pfield */ field_const_rftrx_reg__software_pll_trig_ctrl, /* size */ 7}, 
  { /* pfield */ field_const_rftrx_reg__tx_scale_hp_lp, /* size */ 3}, 
  { /* pfield */ field_const_rftrx_reg__trx_pll_trig_mux_ctrl, /* size */ 5}, 
  { /* pfield */ field_const_rftrx_reg__en_cpll_non_2m_rx, /* size */ 2}, 
  { /* pfield */ field_const_rftrx_reg__pmu_trx_id, /* size */ 2}
};
