/////////////////////////////////////////////////////////////////////////////////
// This file has been automatically generated by register_slave.pl version 05ea59f
/////////////////////////////////////////////////////////////////////////////////

// type declaration
#ifndef __REG_CONST_T
#define __REG_CONST_T

#ifndef REG_CONST_NAME_STRING_MAX_LEN   
#define REG_CONST_NAME_STRING_MAX_LEN 64
#endif // REG_CONST_NAME_STRING_MAX_LEN
#ifndef REG_CONST_DESC_STRING_MAX_LEN
#define REG_CONST_DESC_STRING_MAX_LEN 512
#endif // REG_CONST_DESC_STRING_MAX_LEN
typedef struct {
	char name[REG_CONST_NAME_STRING_MAX_LEN];
	DWORD address;
	DWORD def;
	char desc[REG_CONST_DESC_STRING_MAX_LEN];
} reg_const_t;
typedef struct {
	char name[REG_CONST_NAME_STRING_MAX_LEN];
	char range[32];
	char def[32];
	char access[32];
	char desc[REG_CONST_DESC_STRING_MAX_LEN];
} field_const_t;
typedef struct {
	field_const_t *pfield;
	DWORD size;
} field_const_array_t;
#endif // __REG_CONST_T

#define NUM_REGS__SHAREDMEM_REG  28
/* { reg_const_sharedmem_reg, 28, "sharedmem_reg"},  */ 
static reg_const_t reg_const_sharedmem_reg[NUM_REGS__SHAREDMEM_REG] = {
  {/* name */ "misc_ctrl", /* address */ 0x4414f000, /* default */ 0x00000002, /* description */ "Misc control\n"}, 
  {/* name */ "clnt0_ctrl0", /* address */ 0x4414f040, /* default */ 0x00000001, /* description */ "client control 0\n"}, 
  {/* name */ "clnt0_ctrl1", /* address */ 0x4414f044, /* default */ 0x00000000, /* description */ "client control 1\n"}, 
  {/* name */ "clnt0_ctrl2", /* address */ 0x4414f048, /* default */ 0x00000000, /* description */ "client control 2\n"}, 
  {/* name */ "clnt1_ctrl0", /* address */ 0x4414f050, /* default */ 0x00000001, /* description */ "client control 0\n"}, 
  {/* name */ "clnt1_ctrl1", /* address */ 0x4414f054, /* default */ 0x00000000, /* description */ "client control 1\n"}, 
  {/* name */ "clnt1_ctrl2", /* address */ 0x4414f058, /* default */ 0x00000000, /* description */ "client control 2\n"}, 
  {/* name */ "clnt2_ctrl0", /* address */ 0x4414f060, /* default */ 0x00000001, /* description */ "client control 0\n"}, 
  {/* name */ "clnt2_ctrl1", /* address */ 0x4414f064, /* default */ 0x00000000, /* description */ "client control 1\n"}, 
  {/* name */ "clnt2_ctrl2", /* address */ 0x4414f068, /* default */ 0x00000000, /* description */ "client control 2\n"}, 
  {/* name */ "clnt3_ctrl0", /* address */ 0x4414f070, /* default */ 0x00000001, /* description */ "client control 0\n"}, 
  {/* name */ "clnt3_ctrl1", /* address */ 0x4414f074, /* default */ 0x00000000, /* description */ "client control 1\n"}, 
  {/* name */ "clnt3_ctrl2", /* address */ 0x4414f078, /* default */ 0x00000000, /* description */ "client control 2\n"}, 
  {/* name */ "clnt4_ctrl0", /* address */ 0x4414f080, /* default */ 0x00000001, /* description */ "client control 0\n"}, 
  {/* name */ "clnt4_ctrl1", /* address */ 0x4414f084, /* default */ 0x00000000, /* description */ "client control 1\n"}, 
  {/* name */ "clnt4_ctrl2", /* address */ 0x4414f088, /* default */ 0x00000000, /* description */ "client control 2\n"}, 
  {/* name */ "clnt5_ctrl0", /* address */ 0x4414f090, /* default */ 0x00000001, /* description */ "client control 0\n"}, 
  {/* name */ "clnt5_ctrl1", /* address */ 0x4414f094, /* default */ 0x00000000, /* description */ "client control 1\n"}, 
  {/* name */ "clnt5_ctrl2", /* address */ 0x4414f098, /* default */ 0x00000000, /* description */ "client control 2\n"}, 
  {/* name */ "clnt6_ctrl0", /* address */ 0x4414f0a0, /* default */ 0x00000001, /* description */ "client control 0\n"}, 
  {/* name */ "clnt6_ctrl1", /* address */ 0x4414f0a4, /* default */ 0x00000000, /* description */ "client control 1\n"}, 
  {/* name */ "clnt6_ctrl2", /* address */ 0x4414f0a8, /* default */ 0x00000000, /* description */ "client control 2\n"}, 
  {/* name */ "clnt7_ctrl0", /* address */ 0x4414f0b0, /* default */ 0x00000001, /* description */ "client control 0\n"}, 
  {/* name */ "clnt7_ctrl1", /* address */ 0x4414f0b4, /* default */ 0x00000000, /* description */ "client control 1\n"}, 
  {/* name */ "clnt7_ctrl2", /* address */ 0x4414f0b8, /* default */ 0x00000000, /* description */ "client control 2\n"}, 
  {/* name */ "clnt8_ctrl0", /* address */ 0x4414f0c0, /* default */ 0x00000001, /* description */ "client control 0\n"}, 
  {/* name */ "clnt8_ctrl1", /* address */ 0x4414f0c4, /* default */ 0x00000000, /* description */ "client control 1\n"}, 
  {/* name */ "clnt8_ctrl2", /* address */ 0x4414f0c8, /* default */ 0x00000000, /* description */ "client control 2\n"}
};

field_const_t field_const_sharedmem_reg__misc_ctrl[]  = {
  {/* name */ "ctl_enable", /* range */ "[0:0]", /* default */ "0x0", /* access */ "read-write", /* description */ "Enable the whole block\n"}, 
  {/* name */ "ctl_rdata_valid_if_disable", /* range */ "[1:1]", /* default */ "0x1", /* access */ "read-write", /* description */ "Send out RDATA valid signal if the channel is disabled to avoid hanging the BUS.\n"}, 
  {/* name */ "dummy_field", /* range */ "[7:2]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_sharedmem_reg__clnt0_ctrl0[]  = {
  {/* name */ "enable", /* range */ "[0:0]", /* default */ "0x1", /* access */ "read-write", /* description */ "enable the client\n"}, 
  {/* name */ "enable_panic", /* range */ "[4:4]", /* default */ "0x0", /* access */ "read-write", /* description */ "Enable panic\n"}, 
  {/* name */ "force_panic", /* range */ "[5:5]", /* default */ "0x0", /* access */ "read-write", /* description */ "Force panic\n"}, 
  {/* name */ "addr_offset0", /* range */ "[21:8]", /* default */ "0x00", /* access */ "read-write", /* description */ "Basic address offset\n"}, 
  {/* name */ "dummy_field", /* range */ "[23:22]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_sharedmem_reg__clnt0_ctrl1[]  = {
  {/* name */ "addr_offset1", /* range */ "[13:0]", /* default */ "0x00", /* access */ "read-write", /* description */ "Address offset 1\n"}, 
  {/* name */ "inner_offset1", /* range */ "[29:16]", /* default */ "0x00", /* access */ "read-write", /* description */ "Inner address offset 1\n"}, 
  {/* name */ "dummy_field", /* range */ "[31:30]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_sharedmem_reg__clnt0_ctrl2[]  = {
  {/* name */ "addr_offset2", /* range */ "[13:0]", /* default */ "0x00", /* access */ "read-write", /* description */ "Address offset 2\n"}, 
  {/* name */ "inner_offset2", /* range */ "[29:16]", /* default */ "0x00", /* access */ "read-write", /* description */ "Inner address offset 2\n"}, 
  {/* name */ "dummy_field", /* range */ "[31:30]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_sharedmem_reg__clnt1_ctrl0[]  = {
  {/* name */ "enable", /* range */ "[0:0]", /* default */ "0x1", /* access */ "read-write", /* description */ "enable the client\n"}, 
  {/* name */ "enable_panic", /* range */ "[4:4]", /* default */ "0x0", /* access */ "read-write", /* description */ "Enable panic\n"}, 
  {/* name */ "force_panic", /* range */ "[5:5]", /* default */ "0x0", /* access */ "read-write", /* description */ "Force panic\n"}, 
  {/* name */ "addr_offset0", /* range */ "[21:8]", /* default */ "0x00", /* access */ "read-write", /* description */ "Basic address offset\n"}, 
  {/* name */ "dummy_field", /* range */ "[23:22]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_sharedmem_reg__clnt1_ctrl1[]  = {
  {/* name */ "addr_offset1", /* range */ "[13:0]", /* default */ "0x00", /* access */ "read-write", /* description */ "Address offset 1\n"}, 
  {/* name */ "inner_offset1", /* range */ "[29:16]", /* default */ "0x00", /* access */ "read-write", /* description */ "Inner address offset 1\n"}, 
  {/* name */ "dummy_field", /* range */ "[31:30]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_sharedmem_reg__clnt1_ctrl2[]  = {
  {/* name */ "addr_offset2", /* range */ "[13:0]", /* default */ "0x00", /* access */ "read-write", /* description */ "Address offset 2\n"}, 
  {/* name */ "inner_offset2", /* range */ "[29:16]", /* default */ "0x00", /* access */ "read-write", /* description */ "Inner address offset 2\n"}, 
  {/* name */ "dummy_field", /* range */ "[31:30]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_sharedmem_reg__clnt2_ctrl0[]  = {
  {/* name */ "enable", /* range */ "[0:0]", /* default */ "0x1", /* access */ "read-write", /* description */ "enable the client\n"}, 
  {/* name */ "enable_panic", /* range */ "[4:4]", /* default */ "0x0", /* access */ "read-write", /* description */ "Enable panic\n"}, 
  {/* name */ "force_panic", /* range */ "[5:5]", /* default */ "0x0", /* access */ "read-write", /* description */ "Force panic\n"}, 
  {/* name */ "addr_offset0", /* range */ "[21:8]", /* default */ "0x00", /* access */ "read-write", /* description */ "Basic address offset\n"}, 
  {/* name */ "dummy_field", /* range */ "[23:22]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_sharedmem_reg__clnt2_ctrl1[]  = {
  {/* name */ "addr_offset1", /* range */ "[13:0]", /* default */ "0x00", /* access */ "read-write", /* description */ "Address offset 1\n"}, 
  {/* name */ "inner_offset1", /* range */ "[29:16]", /* default */ "0x00", /* access */ "read-write", /* description */ "Inner address offset 1\n"}, 
  {/* name */ "dummy_field", /* range */ "[31:30]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_sharedmem_reg__clnt2_ctrl2[]  = {
  {/* name */ "addr_offset2", /* range */ "[13:0]", /* default */ "0x00", /* access */ "read-write", /* description */ "Address offset 2\n"}, 
  {/* name */ "inner_offset2", /* range */ "[29:16]", /* default */ "0x00", /* access */ "read-write", /* description */ "Inner address offset 2\n"}, 
  {/* name */ "dummy_field", /* range */ "[31:30]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_sharedmem_reg__clnt3_ctrl0[]  = {
  {/* name */ "enable", /* range */ "[0:0]", /* default */ "0x1", /* access */ "read-write", /* description */ "enable the client\n"}, 
  {/* name */ "enable_panic", /* range */ "[4:4]", /* default */ "0x0", /* access */ "read-write", /* description */ "Enable panic\n"}, 
  {/* name */ "force_panic", /* range */ "[5:5]", /* default */ "0x0", /* access */ "read-write", /* description */ "Force panic\n"}, 
  {/* name */ "addr_offset0", /* range */ "[21:8]", /* default */ "0x00", /* access */ "read-write", /* description */ "Basic address offset\n"}, 
  {/* name */ "dummy_field", /* range */ "[23:22]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_sharedmem_reg__clnt3_ctrl1[]  = {
  {/* name */ "addr_offset1", /* range */ "[13:0]", /* default */ "0x00", /* access */ "read-write", /* description */ "Address offset 1\n"}, 
  {/* name */ "inner_offset1", /* range */ "[29:16]", /* default */ "0x00", /* access */ "read-write", /* description */ "Inner address offset 1\n"}, 
  {/* name */ "dummy_field", /* range */ "[31:30]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_sharedmem_reg__clnt3_ctrl2[]  = {
  {/* name */ "addr_offset2", /* range */ "[13:0]", /* default */ "0x00", /* access */ "read-write", /* description */ "Address offset 2\n"}, 
  {/* name */ "inner_offset2", /* range */ "[29:16]", /* default */ "0x00", /* access */ "read-write", /* description */ "Inner address offset 2\n"}, 
  {/* name */ "dummy_field", /* range */ "[31:30]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_sharedmem_reg__clnt4_ctrl0[]  = {
  {/* name */ "enable", /* range */ "[0:0]", /* default */ "0x1", /* access */ "read-write", /* description */ "enable the client\n"}, 
  {/* name */ "enable_panic", /* range */ "[4:4]", /* default */ "0x0", /* access */ "read-write", /* description */ "Enable panic\n"}, 
  {/* name */ "force_panic", /* range */ "[5:5]", /* default */ "0x0", /* access */ "read-write", /* description */ "Force panic\n"}, 
  {/* name */ "addr_offset0", /* range */ "[21:8]", /* default */ "0x00", /* access */ "read-write", /* description */ "Basic address offset\n"}, 
  {/* name */ "dummy_field", /* range */ "[23:22]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_sharedmem_reg__clnt4_ctrl1[]  = {
  {/* name */ "addr_offset1", /* range */ "[13:0]", /* default */ "0x00", /* access */ "read-write", /* description */ "Address offset 1\n"}, 
  {/* name */ "inner_offset1", /* range */ "[29:16]", /* default */ "0x00", /* access */ "read-write", /* description */ "Inner address offset 1\n"}, 
  {/* name */ "dummy_field", /* range */ "[31:30]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_sharedmem_reg__clnt4_ctrl2[]  = {
  {/* name */ "addr_offset2", /* range */ "[13:0]", /* default */ "0x00", /* access */ "read-write", /* description */ "Address offset 2\n"}, 
  {/* name */ "inner_offset2", /* range */ "[29:16]", /* default */ "0x00", /* access */ "read-write", /* description */ "Inner address offset 2\n"}, 
  {/* name */ "dummy_field", /* range */ "[31:30]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_sharedmem_reg__clnt5_ctrl0[]  = {
  {/* name */ "enable", /* range */ "[0:0]", /* default */ "0x1", /* access */ "read-write", /* description */ "enable the client\n"}, 
  {/* name */ "enable_panic", /* range */ "[4:4]", /* default */ "0x0", /* access */ "read-write", /* description */ "Enable panic\n"}, 
  {/* name */ "force_panic", /* range */ "[5:5]", /* default */ "0x0", /* access */ "read-write", /* description */ "Force panic\n"}, 
  {/* name */ "addr_offset0", /* range */ "[21:8]", /* default */ "0x00", /* access */ "read-write", /* description */ "Basic address offset\n"}, 
  {/* name */ "dummy_field", /* range */ "[23:22]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_sharedmem_reg__clnt5_ctrl1[]  = {
  {/* name */ "addr_offset1", /* range */ "[13:0]", /* default */ "0x00", /* access */ "read-write", /* description */ "Address offset 1\n"}, 
  {/* name */ "inner_offset1", /* range */ "[29:16]", /* default */ "0x00", /* access */ "read-write", /* description */ "Inner address offset 1\n"}, 
  {/* name */ "dummy_field", /* range */ "[31:30]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_sharedmem_reg__clnt5_ctrl2[]  = {
  {/* name */ "addr_offset2", /* range */ "[13:0]", /* default */ "0x00", /* access */ "read-write", /* description */ "Address offset 2\n"}, 
  {/* name */ "inner_offset2", /* range */ "[29:16]", /* default */ "0x00", /* access */ "read-write", /* description */ "Inner address offset 2\n"}, 
  {/* name */ "dummy_field", /* range */ "[31:30]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_sharedmem_reg__clnt6_ctrl0[]  = {
  {/* name */ "enable", /* range */ "[0:0]", /* default */ "0x1", /* access */ "read-write", /* description */ "enable the client\n"}, 
  {/* name */ "enable_panic", /* range */ "[4:4]", /* default */ "0x0", /* access */ "read-write", /* description */ "Enable panic\n"}, 
  {/* name */ "force_panic", /* range */ "[5:5]", /* default */ "0x0", /* access */ "read-write", /* description */ "Force panic\n"}, 
  {/* name */ "addr_offset0", /* range */ "[21:8]", /* default */ "0x00", /* access */ "read-write", /* description */ "Basic address offset\n"}, 
  {/* name */ "dummy_field", /* range */ "[23:22]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_sharedmem_reg__clnt6_ctrl1[]  = {
  {/* name */ "addr_offset1", /* range */ "[13:0]", /* default */ "0x00", /* access */ "read-write", /* description */ "Address offset 1\n"}, 
  {/* name */ "inner_offset1", /* range */ "[29:16]", /* default */ "0x00", /* access */ "read-write", /* description */ "Inner address offset 1\n"}, 
  {/* name */ "dummy_field", /* range */ "[31:30]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_sharedmem_reg__clnt6_ctrl2[]  = {
  {/* name */ "addr_offset2", /* range */ "[13:0]", /* default */ "0x00", /* access */ "read-write", /* description */ "Address offset 2\n"}, 
  {/* name */ "inner_offset2", /* range */ "[29:16]", /* default */ "0x00", /* access */ "read-write", /* description */ "Inner address offset 2\n"}, 
  {/* name */ "dummy_field", /* range */ "[31:30]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_sharedmem_reg__clnt7_ctrl0[]  = {
  {/* name */ "enable", /* range */ "[0:0]", /* default */ "0x1", /* access */ "read-write", /* description */ "enable the client\n"}, 
  {/* name */ "enable_panic", /* range */ "[4:4]", /* default */ "0x0", /* access */ "read-write", /* description */ "Enable panic\n"}, 
  {/* name */ "force_panic", /* range */ "[5:5]", /* default */ "0x0", /* access */ "read-write", /* description */ "Force panic\n"}, 
  {/* name */ "addr_offset0", /* range */ "[21:8]", /* default */ "0x00", /* access */ "read-write", /* description */ "Basic address offset\n"}, 
  {/* name */ "dummy_field", /* range */ "[23:22]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_sharedmem_reg__clnt7_ctrl1[]  = {
  {/* name */ "addr_offset1", /* range */ "[13:0]", /* default */ "0x00", /* access */ "read-write", /* description */ "Address offset 1\n"}, 
  {/* name */ "inner_offset1", /* range */ "[29:16]", /* default */ "0x00", /* access */ "read-write", /* description */ "Inner address offset 1\n"}, 
  {/* name */ "dummy_field", /* range */ "[31:30]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_sharedmem_reg__clnt7_ctrl2[]  = {
  {/* name */ "addr_offset2", /* range */ "[13:0]", /* default */ "0x00", /* access */ "read-write", /* description */ "Address offset 2\n"}, 
  {/* name */ "inner_offset2", /* range */ "[29:16]", /* default */ "0x00", /* access */ "read-write", /* description */ "Inner address offset 2\n"}, 
  {/* name */ "dummy_field", /* range */ "[31:30]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_sharedmem_reg__clnt8_ctrl0[]  = {
  {/* name */ "enable", /* range */ "[0:0]", /* default */ "0x1", /* access */ "read-write", /* description */ "enable the client\n"}, 
  {/* name */ "enable_panic", /* range */ "[4:4]", /* default */ "0x0", /* access */ "read-write", /* description */ "Enable panic\n"}, 
  {/* name */ "force_panic", /* range */ "[5:5]", /* default */ "0x0", /* access */ "read-write", /* description */ "Force panic\n"}, 
  {/* name */ "addr_offset0", /* range */ "[21:8]", /* default */ "0x00", /* access */ "read-write", /* description */ "Basic address offset\n"}, 
  {/* name */ "dummy_field", /* range */ "[23:22]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_sharedmem_reg__clnt8_ctrl1[]  = {
  {/* name */ "addr_offset1", /* range */ "[13:0]", /* default */ "0x00", /* access */ "read-write", /* description */ "Address offset 1\n"}, 
  {/* name */ "inner_offset1", /* range */ "[29:16]", /* default */ "0x00", /* access */ "read-write", /* description */ "Inner address offset 1\n"}, 
  {/* name */ "dummy_field", /* range */ "[31:30]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};
field_const_t field_const_sharedmem_reg__clnt8_ctrl2[]  = {
  {/* name */ "addr_offset2", /* range */ "[13:0]", /* default */ "0x00", /* access */ "read-write", /* description */ "Address offset 2\n"}, 
  {/* name */ "inner_offset2", /* range */ "[29:16]", /* default */ "0x00", /* access */ "read-write", /* description */ "Inner address offset 2\n"}, 
  {/* name */ "dummy_field", /* range */ "[31:30]", /* default */ "0x0", /* access */ "no-access", /* description */ ""}
};

field_const_array_t reg_pnt_list__sharedmem_reg[NUM_REGS__SHAREDMEM_REG] = {
  { /* pfield */ field_const_sharedmem_reg__misc_ctrl, /* size */ 3}, 
  { /* pfield */ field_const_sharedmem_reg__clnt0_ctrl0, /* size */ 5}, 
  { /* pfield */ field_const_sharedmem_reg__clnt0_ctrl1, /* size */ 3}, 
  { /* pfield */ field_const_sharedmem_reg__clnt0_ctrl2, /* size */ 3}, 
  { /* pfield */ field_const_sharedmem_reg__clnt1_ctrl0, /* size */ 5}, 
  { /* pfield */ field_const_sharedmem_reg__clnt1_ctrl1, /* size */ 3}, 
  { /* pfield */ field_const_sharedmem_reg__clnt1_ctrl2, /* size */ 3}, 
  { /* pfield */ field_const_sharedmem_reg__clnt2_ctrl0, /* size */ 5}, 
  { /* pfield */ field_const_sharedmem_reg__clnt2_ctrl1, /* size */ 3}, 
  { /* pfield */ field_const_sharedmem_reg__clnt2_ctrl2, /* size */ 3}, 
  { /* pfield */ field_const_sharedmem_reg__clnt3_ctrl0, /* size */ 5}, 
  { /* pfield */ field_const_sharedmem_reg__clnt3_ctrl1, /* size */ 3}, 
  { /* pfield */ field_const_sharedmem_reg__clnt3_ctrl2, /* size */ 3}, 
  { /* pfield */ field_const_sharedmem_reg__clnt4_ctrl0, /* size */ 5}, 
  { /* pfield */ field_const_sharedmem_reg__clnt4_ctrl1, /* size */ 3}, 
  { /* pfield */ field_const_sharedmem_reg__clnt4_ctrl2, /* size */ 3}, 
  { /* pfield */ field_const_sharedmem_reg__clnt5_ctrl0, /* size */ 5}, 
  { /* pfield */ field_const_sharedmem_reg__clnt5_ctrl1, /* size */ 3}, 
  { /* pfield */ field_const_sharedmem_reg__clnt5_ctrl2, /* size */ 3}, 
  { /* pfield */ field_const_sharedmem_reg__clnt6_ctrl0, /* size */ 5}, 
  { /* pfield */ field_const_sharedmem_reg__clnt6_ctrl1, /* size */ 3}, 
  { /* pfield */ field_const_sharedmem_reg__clnt6_ctrl2, /* size */ 3}, 
  { /* pfield */ field_const_sharedmem_reg__clnt7_ctrl0, /* size */ 5}, 
  { /* pfield */ field_const_sharedmem_reg__clnt7_ctrl1, /* size */ 3}, 
  { /* pfield */ field_const_sharedmem_reg__clnt7_ctrl2, /* size */ 3}, 
  { /* pfield */ field_const_sharedmem_reg__clnt8_ctrl0, /* size */ 5}, 
  { /* pfield */ field_const_sharedmem_reg__clnt8_ctrl1, /* size */ 3}, 
  { /* pfield */ field_const_sharedmem_reg__clnt8_ctrl2, /* size */ 3}
};
