#ifndef BOOTRAM_MEM_H
#define BOOTRAM_MEM_H

#define BOOTRAM_SIZE					0x1000

#define BOOTRAM_FLASH_BASE		0x00000000

#define BOOTRAM_CODE_START		0x200000
#define BOOTRAM_CODE_SIZE		0xF60
#define BOOTRAM_CODE_END			(BOOTRAM_CODE_START + BOOTRAM_CODE_SIZE)

#define BOOTRAM_RW_START		BOOTRAM_CODE_END
#define BOOTRAM_RW_SIZE		0x20
#define BOOTRAM_RW_END			(BOOTRAM_RW_START + BOOTRAM_RW_SIZE)

#define BOOTRAM_BOOTCFG_START				0x200F80
#define BOOTRAM_BOOTCFG_SIZE					0x80
#define BOOTRAM_BOOTCFG_END					(BOOTRAM_BOOTCFG_START + BOOTRAM_BOOTCFG_SIZE)


#endif
